-- RICETTE v9: le 82 ricette del file EMPATHY_FOOD_KNOWLEDGE_BASE_v9_PROTEIN_SHAKE_RECIPES
-- (15 esistenti + 67 nuove, di cui 8 shake proteici) con le colonne v9
-- family/tier/selection_weight/meals (DDL 20260821090000).
--
-- Generata da scratchpad/gen_v9_recipes_migration.py (v9_recipes.json + v6_mapping.json
-- + dump prod nutrition_menu_foods del 21 ago). Verifiche in generazione: 405/405
-- componenti risolti (EMP_CAT via mapping, EMP_ADD_001..005 -> canonical nuovi,
-- TECH_WATER -> neutro), somme grammi in [99,101], slug univoci, 15/15 slug = prod.
--
-- I componenti delle 15 ricette ESISTENTI non si toccano (byte-identici al file v9);
-- l'upsert non tocca nemmeno note/is_active delle esistenti. Le 2 ricette con caseina
-- portano la nota REVIEW (P06) e si inseriscono comunque.
--
-- Rieseguibile: upsert su recipe_key; componenti delle 67 nuove in delete+insert.
-- Prerequisiti: 20260821090000 (colonne) e 20260821090300 (canonical EMP_ADD) applicate.

insert into public.nutrition_recipes (recipe_key, label_it, is_active, source_ref, source_version, frequency, max_week, family, tier, selection_weight, meals, note) values
('pizza_margherita', 'Pizza Margherita', true, 'EMP_RECIPE_001', 'mario_v9', 'OCCASIONAL', 1, 'PIZZA', 'OCCASIONAL', 15, '["lunch", "dinner"]'::jsonb, NULL),
('pasta_alla_carbonara', 'Pasta alla carbonara', true, 'EMP_RECIPE_002', 'mario_v9', 'OCCASIONAL', 1, NULL, 'OCCASIONAL', 15, '["lunch", "dinner"]'::jsonb, NULL),
('pasta_al_ragu', 'Pasta al ragù', true, 'EMP_RECIPE_003', 'mario_v9', 'ROTATION', 2, NULL, 'ROTATION', 55, '["lunch", "dinner"]'::jsonb, NULL),
('lasagne_al_ragu', 'Lasagne al ragù', true, 'EMP_RECIPE_004', 'mario_v9', 'OCCASIONAL', 1, 'LASAGNE', 'OCCASIONAL', 15, '["lunch", "dinner"]'::jsonb, NULL),
('hamburger_completo', 'Hamburger completo', true, 'EMP_RECIPE_005', 'mario_v9', 'OCCASIONAL', 1, 'BURGER', 'OCCASIONAL', 15, '["lunch", "dinner"]'::jsonb, NULL),
('cotoletta_di_pollo', 'Cotoletta di pollo', true, 'EMP_RECIPE_006', 'mario_v9', 'OCCASIONAL', 1, NULL, 'OCCASIONAL', 15, '["lunch", "dinner"]'::jsonb, NULL),
('piadina_prosciutto_e_mozzarella', 'Piadina prosciutto e mozzarella', true, 'EMP_RECIPE_007', 'mario_v9', 'ROTATION', 2, NULL, 'ROTATION', 35, '["lunch", "dinner"]'::jsonb, NULL),
('risotto_al_parmigiano', 'Risotto al parmigiano', true, 'EMP_RECIPE_008', 'mario_v9', 'ROTATION', 2, NULL, 'ROTATION', 55, '["lunch", "dinner"]'::jsonb, NULL),
('pasta_al_tonno_e_pomodoro', 'Pasta al tonno e pomodoro', true, 'EMP_RECIPE_009', 'mario_v9', 'ROTATION', 2, NULL, 'ROTATION', 55, '["lunch", "dinner"]'::jsonb, NULL),
('gnocchi_al_pomodoro', 'Gnocchi al pomodoro', true, 'EMP_RECIPE_010', 'mario_v9', 'ROTATION', 2, NULL, 'ROTATION', 55, '["lunch", "dinner"]'::jsonb, NULL),
('pasta_al_pesto', 'Pasta al pesto', true, 'EMP_RECIPE_011', 'mario_v9', 'ROTATION', 2, NULL, 'ROTATION', 55, '["lunch", "dinner"]'::jsonb, NULL),
('toast_prosciutto_e_formaggio', 'Toast prosciutto e formaggio', true, 'EMP_RECIPE_012', 'mario_v9', 'ROTATION', 2, NULL, 'ROTATION', 55, '["lunch", "dinner"]'::jsonb, NULL),
('porridge_avena_e_banana', 'Porridge avena e banana', true, 'EMP_RECIPE_013', 'mario_v9', 'ROTATION', 2, NULL, 'ROTATION', 55, '["breakfast"]'::jsonb, NULL),
('smoothie_yogurt_e_frutti_rossi', 'Smoothie yogurt e frutti rossi', true, 'EMP_RECIPE_014', 'mario_v9', 'ROTATION', 2, NULL, 'ROTATION', 55, '["breakfast"]'::jsonb, NULL),
('pancake_avena_e_uova', 'Pancake avena e uova', true, 'EMP_RECIPE_015', 'mario_v9', 'ROTATION', 2, NULL, 'ROTATION', 55, '["breakfast"]'::jsonb, NULL),
('pizza_marinara', 'Pizza Marinara', true, 'EMP_RECIPE_016', 'mario_v9', 'OCCASIONAL', 1, 'PIZZA', 'OCCASIONAL', 15, '["lunch", "dinner"]'::jsonb, NULL),
('pizza_prosciutto_cotto', 'Pizza prosciutto cotto', true, 'EMP_RECIPE_017', 'mario_v9', 'OCCASIONAL', 1, 'PIZZA', 'OCCASIONAL', 15, '["lunch", "dinner"]'::jsonb, NULL),
('pizza_prosciutto_e_funghi', 'Pizza prosciutto e funghi', true, 'EMP_RECIPE_018', 'mario_v9', 'OCCASIONAL', 1, 'PIZZA', 'OCCASIONAL', 15, '["lunch", "dinner"]'::jsonb, NULL),
('pizza_tonno_e_cipolla', 'Pizza tonno e cipolla', true, 'EMP_RECIPE_019', 'mario_v9', 'OCCASIONAL', 1, 'PIZZA', 'OCCASIONAL', 15, '["lunch", "dinner"]'::jsonb, NULL),
('pizza_verdure_grigliate', 'Pizza verdure grigliate', true, 'EMP_RECIPE_020', 'mario_v9', 'OCCASIONAL', 1, 'PIZZA', 'OCCASIONAL', 15, '["lunch", "dinner"]'::jsonb, NULL),
('pizza_bresaola_e_rucola', 'Pizza bresaola e rucola', true, 'EMP_RECIPE_021', 'mario_v9', 'OCCASIONAL', 1, 'PIZZA', 'OCCASIONAL', 15, '["lunch", "dinner"]'::jsonb, NULL),
('pizza_diavola', 'Pizza diavola', true, 'EMP_RECIPE_022', 'mario_v9', 'OCCASIONAL', 1, 'PIZZA', 'OCCASIONAL', 15, '["lunch", "dinner"]'::jsonb, NULL),
('pizza_quattro_formaggi', 'Pizza quattro formaggi', true, 'EMP_RECIPE_023', 'mario_v9', 'OCCASIONAL', 1, 'PIZZA', 'OCCASIONAL', 15, '["lunch", "dinner"]'::jsonb, NULL),
('pizza_capricciosa', 'Pizza capricciosa', true, 'EMP_RECIPE_024', 'mario_v9', 'OCCASIONAL', 1, 'PIZZA', 'OCCASIONAL', 15, '["lunch", "dinner"]'::jsonb, NULL),
('pizza_fiordilatte_e_pomodorini', 'Pizza fiordilatte e pomodorini', true, 'EMP_RECIPE_025', 'mario_v9', 'OCCASIONAL', 1, 'PIZZA', 'OCCASIONAL', 15, '["lunch", "dinner"]'::jsonb, NULL),
('pizza_wurstel', 'Pizza wurstel', true, 'EMP_RECIPE_026', 'mario_v9', 'OCCASIONAL', 1, 'PIZZA', 'OCCASIONAL', 15, '["lunch", "dinner"]'::jsonb, NULL),
('cheeseburger_classico', 'Cheeseburger classico', true, 'EMP_RECIPE_027', 'mario_v9', 'OCCASIONAL', 1, 'BURGER', 'OCCASIONAL', 15, '["lunch", "dinner"]'::jsonb, NULL),
('chicken_burger', 'Chicken burger', true, 'EMP_RECIPE_028', 'mario_v9', 'OCCASIONAL', 1, 'BURGER', 'OCCASIONAL', 15, '["lunch", "dinner"]'::jsonb, NULL),
('turkey_burger', 'Turkey burger', true, 'EMP_RECIPE_029', 'mario_v9', 'OCCASIONAL', 1, 'BURGER', 'OCCASIONAL', 15, '["lunch", "dinner"]'::jsonb, NULL),
('hamburger_manzo_e_uovo', 'Hamburger manzo e uovo', true, 'EMP_RECIPE_030', 'mario_v9', 'OCCASIONAL', 1, 'BURGER', 'OCCASIONAL', 15, '["lunch", "dinner"]'::jsonb, NULL),
('pasta_al_pomodoro', 'Pasta al pomodoro', true, 'EMP_RECIPE_031', 'mario_v9', 'COMMON', 2, 'PASTA', 'CORE', 60, '["lunch", "dinner"]'::jsonb, NULL),
('pasta_pomodoro_e_mozzarella', 'Pasta pomodoro e mozzarella', true, 'EMP_RECIPE_032', 'mario_v9', 'COMMON', 2, 'PASTA', 'CORE', 50, '["lunch", "dinner"]'::jsonb, NULL),
('pasta_zucchine_e_parmigiano', 'Pasta zucchine e parmigiano', true, 'EMP_RECIPE_033', 'mario_v9', 'COMMON', 2, 'PASTA', 'CORE', 50, '["lunch", "dinner"]'::jsonb, NULL),
('pasta_pollo_e_pomodoro', 'Pasta pollo e pomodoro', true, 'EMP_RECIPE_034', 'mario_v9', 'COMMON', 2, 'PASTA', 'CORE', 45, '["lunch", "dinner"]'::jsonb, NULL),
('pasta_tonno_e_olive', 'Pasta tonno e olive', true, 'EMP_RECIPE_035', 'mario_v9', 'ROTATION', 1, 'PASTA', 'ROTATION', 35, '["lunch", "dinner"]'::jsonb, NULL),
('pasta_salmone_e_zucchine', 'Pasta salmone e zucchine', true, 'EMP_RECIPE_036', 'mario_v9', 'ROTATION', 1, 'PASTA', 'ROTATION', 35, '["lunch", "dinner"]'::jsonb, NULL),
('pasta_ricotta_e_spinaci', 'Pasta ricotta e spinaci', true, 'EMP_RECIPE_037', 'mario_v9', 'ROTATION', 1, 'PASTA', 'ROTATION', 30, '["lunch", "dinner"]'::jsonb, NULL),
('pasta_alla_amatriciana', 'Pasta alla amatriciana', true, 'EMP_RECIPE_038', 'mario_v9', 'ROTATION', 1, 'PASTA', 'ROTATION', 25, '["lunch", "dinner"]'::jsonb, NULL),
('pasta_melanzane_e_mozzarella', 'Pasta melanzane e mozzarella', true, 'EMP_RECIPE_039', 'mario_v9', 'ROTATION', 1, 'PASTA', 'ROTATION', 30, '["lunch", "dinner"]'::jsonb, NULL),
('pasta_gamberi_e_zucchine', 'Pasta gamberi e zucchine', true, 'EMP_RECIPE_040', 'mario_v9', 'ROTATION', 1, 'PASTA', 'ROTATION', 35, '["lunch", "dinner"]'::jsonb, NULL),
('riso_pollo_e_zucchine', 'Riso pollo e zucchine', true, 'EMP_RECIPE_041', 'mario_v9', 'COMMON', 2, 'RICE', 'CORE', 55, '["lunch", "dinner"]'::jsonb, NULL),
('riso_tacchino_e_carote', 'Riso tacchino e carote', true, 'EMP_RECIPE_042', 'mario_v9', 'COMMON', 2, 'RICE', 'CORE', 55, '["lunch", "dinner"]'::jsonb, NULL),
('riso_tonno_e_pomodoro', 'Riso tonno e pomodoro', true, 'EMP_RECIPE_043', 'mario_v9', 'COMMON', 2, 'RICE', 'CORE', 45, '["lunch", "dinner"]'::jsonb, NULL),
('risotto_alle_zucchine', 'Risotto alle zucchine', true, 'EMP_RECIPE_044', 'mario_v9', 'COMMON', 2, 'RISOTTO', 'CORE', 45, '["lunch", "dinner"]'::jsonb, NULL),
('risotto_ai_funghi', 'Risotto ai funghi', true, 'EMP_RECIPE_045', 'mario_v9', 'ROTATION', 1, 'RISOTTO', 'ROTATION', 35, '["lunch", "dinner"]'::jsonb, NULL),
('risotto_gamberi_e_zucchine', 'Risotto gamberi e zucchine', true, 'EMP_RECIPE_046', 'mario_v9', 'ROTATION', 1, 'RISOTTO', 'ROTATION', 30, '["lunch", "dinner"]'::jsonb, NULL),
('risotto_salmone_e_zucchine', 'Risotto salmone e zucchine', true, 'EMP_RECIPE_047', 'mario_v9', 'ROTATION', 1, 'RISOTTO', 'ROTATION', 28, '["lunch", "dinner"]'::jsonb, NULL),
('riso_piselli_e_parmigiano', 'Riso piselli e parmigiano', true, 'EMP_RECIPE_048', 'mario_v9', 'ROTATION', 1, 'RICE', 'ROTATION', 35, '["lunch", "dinner"]'::jsonb, NULL),
('cous_cous_pollo_e_verdure', 'Cous cous pollo e verdure', true, 'EMP_RECIPE_049', 'mario_v9', 'COMMON', 2, 'COUSCOUS', 'CORE', 45, '["lunch", "dinner"]'::jsonb, NULL),
('farro_tonno_e_pomodorini', 'Farro tonno e pomodorini', true, 'EMP_RECIPE_050', 'mario_v9', 'COMMON', 2, 'FARRO', 'CORE', 40, '["lunch", "dinner"]'::jsonb, NULL),
('lasagne_alle_verdure', 'Lasagne alle verdure', true, 'EMP_RECIPE_051', 'mario_v9', 'ROTATION', 1, 'LASAGNE', 'ROTATION', 25, '["lunch", "dinner"]'::jsonb, NULL),
('lasagne_ricotta_e_spinaci', 'Lasagne ricotta e spinaci', true, 'EMP_RECIPE_052', 'mario_v9', 'ROTATION', 1, 'LASAGNE', 'ROTATION', 25, '["lunch", "dinner"]'::jsonb, NULL),
('lasagne_salmone_e_zucchine', 'Lasagne salmone e zucchine', true, 'EMP_RECIPE_053', 'mario_v9', 'ROTATION', 1, 'LASAGNE', 'ROTATION', 20, '["lunch", "dinner"]'::jsonb, NULL),
('lasagne_pollo_e_spinaci', 'Lasagne pollo e spinaci', true, 'EMP_RECIPE_054', 'mario_v9', 'ROTATION', 1, 'LASAGNE', 'ROTATION', 20, '["lunch", "dinner"]'::jsonb, NULL),
('crespelle_prosciutto_e_mozzarella', 'Crespelle prosciutto e mozzarella', true, 'EMP_RECIPE_055', 'mario_v9', 'ROTATION', 1, 'CRESPELLE', 'ROTATION', 25, '["lunch", "dinner"]'::jsonb, NULL),
('crespelle_ricotta_e_spinaci', 'Crespelle ricotta e spinaci', true, 'EMP_RECIPE_056', 'mario_v9', 'ROTATION', 1, 'CRESPELLE', 'ROTATION', 25, '["lunch", "dinner"]'::jsonb, NULL),
('crespelle_pollo_e_zucchine', 'Crespelle pollo e zucchine', true, 'EMP_RECIPE_057', 'mario_v9', 'ROTATION', 1, 'CRESPELLE', 'ROTATION', 22, '["lunch", "dinner"]'::jsonb, NULL),
('crespelle_salmone_e_zucchine', 'Crespelle salmone e zucchine', true, 'EMP_RECIPE_058', 'mario_v9', 'ROTATION', 1, 'CRESPELLE', 'ROTATION', 20, '["lunch", "dinner"]'::jsonb, NULL),
('pollo_alla_pizzaiola', 'Pollo alla pizzaiola', true, 'EMP_RECIPE_059', 'mario_v9', 'COMMON', 2, 'MEAT_DISH', 'CORE', 45, '["lunch", "dinner"]'::jsonb, NULL),
('pollo_con_zucchine', 'Pollo con zucchine', true, 'EMP_RECIPE_060', 'mario_v9', 'COMMON', 2, 'MEAT_DISH', 'CORE', 45, '["lunch", "dinner"]'::jsonb, NULL),
('tacchino_con_carote', 'Tacchino con carote', true, 'EMP_RECIPE_061', 'mario_v9', 'COMMON', 2, 'MEAT_DISH', 'CORE', 45, '["lunch", "dinner"]'::jsonb, NULL),
('tacchino_alla_pizzaiola', 'Tacchino alla pizzaiola', true, 'EMP_RECIPE_062', 'mario_v9', 'COMMON', 2, 'MEAT_DISH', 'CORE', 40, '["lunch", "dinner"]'::jsonb, NULL),
('straccetti_di_manzo_con_rucola_e_parmigiano', 'Straccetti di manzo con rucola e parmigiano', true, 'EMP_RECIPE_063', 'mario_v9', 'ROTATION', 1, 'MEAT_DISH', 'ROTATION', 30, '["lunch", "dinner"]'::jsonb, NULL),
('polpette_di_manzo_al_pomodoro', 'Polpette di manzo al pomodoro', true, 'EMP_RECIPE_064', 'mario_v9', 'ROTATION', 1, 'MEAT_DISH', 'ROTATION', 30, '["lunch", "dinner"]'::jsonb, NULL),
('polpettone_di_tacchino_e_spinaci', 'Polpettone di tacchino e spinaci', true, 'EMP_RECIPE_065', 'mario_v9', 'ROTATION', 1, 'MEAT_DISH', 'ROTATION', 25, '["lunch", "dinner"]'::jsonb, NULL),
('pollo_al_forno_con_patate', 'Pollo al forno con patate', true, 'EMP_RECIPE_066', 'mario_v9', 'COMMON', 2, 'MEAT_DISH', 'CORE', 40, '["lunch", "dinner"]'::jsonb, NULL),
('salmone_al_forno_con_zucchine', 'Salmone al forno con zucchine', true, 'EMP_RECIPE_067', 'mario_v9', 'COMMON', 2, 'FISH_DISH', 'CORE', 40, '["lunch", "dinner"]'::jsonb, NULL),
('merluzzo_al_pomodoro', 'Merluzzo al pomodoro', true, 'EMP_RECIPE_068', 'mario_v9', 'COMMON', 2, 'FISH_DISH', 'CORE', 45, '["lunch", "dinner"]'::jsonb, NULL),
('merluzzo_con_patate_e_pomodori', 'Merluzzo con patate e pomodori', true, 'EMP_RECIPE_069', 'mario_v9', 'COMMON', 2, 'FISH_DISH', 'CORE', 40, '["lunch", "dinner"]'::jsonb, NULL),
('branzino_al_forno_con_pomodorini', 'Branzino al forno con pomodorini', true, 'EMP_RECIPE_070', 'mario_v9', 'ROTATION', 1, 'FISH_DISH', 'ROTATION', 30, '["lunch", "dinner"]'::jsonb, NULL),
('orata_con_patate', 'Orata con patate', true, 'EMP_RECIPE_071', 'mario_v9', 'ROTATION', 1, 'FISH_DISH', 'ROTATION', 30, '["lunch", "dinner"]'::jsonb, NULL),
('tonno_con_pomodori_e_olive', 'Tonno con pomodori e olive', true, 'EMP_RECIPE_072', 'mario_v9', 'COMMON', 2, 'FISH_DISH', 'CORE', 35, '["lunch", "dinner"]'::jsonb, NULL),
('gamberi_con_riso_e_zucchine', 'Gamberi con riso e zucchine', true, 'EMP_RECIPE_073', 'mario_v9', 'ROTATION', 1, 'FISH_DISH', 'ROTATION', 30, '["lunch", "dinner"]'::jsonb, NULL),
('cozze_al_pomodoro_con_pane', 'Cozze al pomodoro con pane', true, 'EMP_RECIPE_074', 'mario_v9', 'ROTATION', 1, 'FISH_DISH', 'ROTATION', 25, '["lunch", "dinner"]'::jsonb, NULL),
('shake_whey_ultrafiltrate_e_mandorla', 'Shake whey ultrafiltrate e mandorla', true, 'EMP_RECIPE_075', 'mario_v9', 'ROTATION', 3, 'PROTEIN_SHAKE_LIGHT', 'ROTATION', 30, '["breakfast", "snack"]'::jsonb, NULL),
('shake_whey_ultrafiltrate_soia_e_banana', 'Shake whey ultrafiltrate, soia e banana', true, 'EMP_RECIPE_076', 'mario_v9', 'ROTATION', 3, 'PROTEIN_SHAKE_ENERGY', 'ROTATION', 30, '["breakfast", "snack"]'::jsonb, NULL),
('shake_whey_e_latte_scremato', 'Shake whey e latte scremato', true, 'EMP_RECIPE_077', 'mario_v9', 'ROTATION', 3, 'PROTEIN_SHAKE_CLASSIC', 'ROTATION', 30, '["breakfast", "snack"]'::jsonb, NULL),
('crema_caseina_e_yogurt_bianco', 'Crema caseina e yogurt bianco', true, 'EMP_RECIPE_078', 'mario_v9', 'ROTATION', 3, 'PROTEIN_CREAM', 'ROTATION', 30, '["breakfast", "snack"]'::jsonb, 'REVIEW (P06): usa caseina micellare a profilo EMPATHY generico — valori non di etichetta, da sostituire con un prodotto configurato.'),
('shake_caseina_e_latte_parzialmente_scremato', 'Shake caseina e latte parzialmente scremato', true, 'EMP_RECIPE_079', 'mario_v9', 'ROTATION', 3, 'PROTEIN_SHAKE_SLOW', 'ROTATION', 30, '["breakfast", "snack"]'::jsonb, 'REVIEW (P06): usa caseina micellare a profilo EMPATHY generico — valori non di etichetta, da sostituire con un prodotto configurato.'),
('shake_proteine_vegetali_e_mandorla', 'Shake proteine vegetali e mandorla', true, 'EMP_RECIPE_080', 'mario_v9', 'ROTATION', 3, 'PLANT_PROTEIN_SHAKE', 'ROTATION', 30, '["breakfast", "snack"]'::jsonb, NULL),
('shake_proteine_vegetali_e_soia', 'Shake proteine vegetali e soia', true, 'EMP_RECIPE_081', 'mario_v9', 'ROTATION', 3, 'PLANT_PROTEIN_SHAKE', 'ROTATION', 30, '["breakfast", "snack"]'::jsonb, NULL),
('shake_whey_banana_e_burro_di_arachidi', 'Shake whey banana e burro di arachidi', true, 'EMP_RECIPE_082', 'mario_v9', 'ROTATION', 3, 'PROTEIN_SHAKE_HIGH_ENERGY', 'ROTATION', 30, '["breakfast", "snack"]'::jsonb, NULL)
on conflict (recipe_key) do update set
  label_it         = excluded.label_it,
  source_ref       = excluded.source_ref,
  source_version   = excluded.source_version,
  frequency        = excluded.frequency,
  max_week         = excluded.max_week,
  family           = excluded.family,
  tier             = excluded.tier,
  selection_weight = excluded.selection_weight,
  meals            = excluded.meals,
  updated_at       = now();
-- (note e is_active NON nel DO UPDATE: le esistenti conservano le loro; le 2 note
--  REVIEW arrivano con l'INSERT delle ricette caseina, che sono nuove.)

delete from public.nutrition_recipe_components c
using public.nutrition_recipes r
where c.recipe_id = r.id and r.recipe_key in (
  'branzino_al_forno_con_pomodorini',
  'cheeseburger_classico',
  'chicken_burger',
  'cous_cous_pollo_e_verdure',
  'cozze_al_pomodoro_con_pane',
  'crema_caseina_e_yogurt_bianco',
  'crespelle_pollo_e_zucchine',
  'crespelle_prosciutto_e_mozzarella',
  'crespelle_ricotta_e_spinaci',
  'crespelle_salmone_e_zucchine',
  'farro_tonno_e_pomodorini',
  'gamberi_con_riso_e_zucchine',
  'hamburger_manzo_e_uovo',
  'lasagne_alle_verdure',
  'lasagne_pollo_e_spinaci',
  'lasagne_ricotta_e_spinaci',
  'lasagne_salmone_e_zucchine',
  'merluzzo_al_pomodoro',
  'merluzzo_con_patate_e_pomodori',
  'orata_con_patate',
  'pasta_al_pomodoro',
  'pasta_alla_amatriciana',
  'pasta_gamberi_e_zucchine',
  'pasta_melanzane_e_mozzarella',
  'pasta_pollo_e_pomodoro',
  'pasta_pomodoro_e_mozzarella',
  'pasta_ricotta_e_spinaci',
  'pasta_salmone_e_zucchine',
  'pasta_tonno_e_olive',
  'pasta_zucchine_e_parmigiano',
  'pizza_bresaola_e_rucola',
  'pizza_capricciosa',
  'pizza_diavola',
  'pizza_fiordilatte_e_pomodorini',
  'pizza_marinara',
  'pizza_prosciutto_cotto',
  'pizza_prosciutto_e_funghi',
  'pizza_quattro_formaggi',
  'pizza_tonno_e_cipolla',
  'pizza_verdure_grigliate',
  'pizza_wurstel',
  'pollo_al_forno_con_patate',
  'pollo_alla_pizzaiola',
  'pollo_con_zucchine',
  'polpette_di_manzo_al_pomodoro',
  'polpettone_di_tacchino_e_spinaci',
  'riso_piselli_e_parmigiano',
  'riso_pollo_e_zucchine',
  'riso_tacchino_e_carote',
  'riso_tonno_e_pomodoro',
  'risotto_ai_funghi',
  'risotto_alle_zucchine',
  'risotto_gamberi_e_zucchine',
  'risotto_salmone_e_zucchine',
  'salmone_al_forno_con_zucchine',
  'shake_caseina_e_latte_parzialmente_scremato',
  'shake_proteine_vegetali_e_mandorla',
  'shake_proteine_vegetali_e_soia',
  'shake_whey_banana_e_burro_di_arachidi',
  'shake_whey_e_latte_scremato',
  'shake_whey_ultrafiltrate_e_mandorla',
  'shake_whey_ultrafiltrate_soia_e_banana',
  'straccetti_di_manzo_con_rucola_e_parmigiano',
  'tacchino_alla_pizzaiola',
  'tacchino_con_carote',
  'tonno_con_pomodori_e_olive',
  'turkey_burger'
);

insert into public.nutrition_recipe_components (recipe_id, position, canonical_key, fdc_id, label_it, grams_per_100g, is_neutral)
select r.id, v.position, v.canonical_key, v.fdc_id, v.label_it, v.grams_per_100g, v.is_neutral
from (values
('pizza_marinara', 1, 'bread_white', 174925, 'Pane', 65, false),
('pizza_marinara', 2, 'tomatoes_canned', 170138, 'Pomodori pelati', 28, false),
('pizza_marinara', 3, 'olive_oil', 171413, 'Olio EVO', 5, false),
('pizza_marinara', 4, NULL, NULL, 'Acqua / brodo neutro', 2, true),
('pizza_prosciutto_cotto', 1, 'bread_white', 174925, 'Pane', 48, false),
('pizza_prosciutto_cotto', 2, 'tomatoes_canned', 170138, 'Pomodori pelati', 18, false),
('pizza_prosciutto_cotto', 3, 'mozzarella', 170847, 'Mozzarella', 16, false),
('pizza_prosciutto_cotto', 4, 'ham_cooked', 332397, 'Prosciutto cotto', 12, false),
('pizza_prosciutto_cotto', 5, 'olive_oil', 171413, 'Olio EVO', 3, false),
('pizza_prosciutto_cotto', 6, NULL, NULL, 'Acqua / brodo neutro', 3, true),
('pizza_prosciutto_e_funghi', 1, 'bread_white', 174925, 'Pane', 46, false),
('pizza_prosciutto_e_funghi', 2, 'tomatoes_canned', 170138, 'Pomodori pelati', 18, false),
('pizza_prosciutto_e_funghi', 3, 'mozzarella', 170847, 'Mozzarella', 15, false),
('pizza_prosciutto_e_funghi', 4, 'ham_cooked', 332397, 'Prosciutto cotto', 10, false),
('pizza_prosciutto_e_funghi', 5, 'mushrooms_white', 169251, 'Funghi champignon', 8, false),
('pizza_prosciutto_e_funghi', 6, 'olive_oil', 171413, 'Olio EVO', 3, false),
('pizza_tonno_e_cipolla', 1, 'bread_white', 174925, 'Pane', 45, false),
('pizza_tonno_e_cipolla', 2, 'tomatoes_canned', 170138, 'Pomodori pelati', 18, false),
('pizza_tonno_e_cipolla', 3, 'mozzarella', 170847, 'Mozzarella', 12, false),
('pizza_tonno_e_cipolla', 4, 'tuna_canned_water', 171986, 'Tonno al naturale', 12, false),
('pizza_tonno_e_cipolla', 5, 'onion', 170000, 'Cipolla', 8, false),
('pizza_tonno_e_cipolla', 6, 'olive_oil', 171413, 'Olio EVO', 3, false),
('pizza_tonno_e_cipolla', 7, NULL, NULL, 'Acqua / brodo neutro', 2, true),
('pizza_verdure_grigliate', 1, 'bread_white', 174925, 'Pane', 45, false),
('pizza_verdure_grigliate', 2, 'tomatoes_canned', 170138, 'Pomodori pelati', 15, false),
('pizza_verdure_grigliate', 3, 'mozzarella', 170847, 'Mozzarella', 12, false),
('pizza_verdure_grigliate', 4, 'zucchini_raw', 169291, 'Zucchine', 8, false),
('pizza_verdure_grigliate', 5, 'eggplant', 2685577, 'Melanzane', 8, false),
('pizza_verdure_grigliate', 6, 'bell_pepper_red', 170108, 'Peperoni', 7, false),
('pizza_verdure_grigliate', 7, 'olive_oil', 171413, 'Olio EVO', 3, false),
('pizza_verdure_grigliate', 8, NULL, NULL, 'Acqua / brodo neutro', 2, true),
('pizza_bresaola_e_rucola', 1, 'bread_white', 174925, 'Pane', 47, false),
('pizza_bresaola_e_rucola', 2, 'tomatoes_canned', 170138, 'Pomodori pelati', 15, false),
('pizza_bresaola_e_rucola', 3, 'mozzarella', 170847, 'Mozzarella', 15, false),
('pizza_bresaola_e_rucola', 4, 'bresaola', 170604, 'Bresaola', 12, false),
('pizza_bresaola_e_rucola', 5, 'arugula_raw', 169387, 'Rucola', 7, false),
('pizza_bresaola_e_rucola', 6, 'olive_oil', 171413, 'Olio EVO', 3, false),
('pizza_bresaola_e_rucola', 7, NULL, NULL, 'Acqua / brodo neutro', 1, true),
('pizza_diavola', 1, 'bread_white', 174925, 'Pane', 47, false),
('pizza_diavola', 2, 'tomatoes_canned', 170138, 'Pomodori pelati', 18, false),
('pizza_diavola', 3, 'mozzarella', 170847, 'Mozzarella', 17, false),
('pizza_diavola', 4, 'salame', 174603, 'Salame', 12, false),
('pizza_diavola', 5, 'olive_oil', 171413, 'Olio EVO', 3, false),
('pizza_diavola', 6, NULL, NULL, 'Acqua / brodo neutro', 3, true),
('pizza_quattro_formaggi', 1, 'bread_white', 174925, 'Pane', 50, false),
('pizza_quattro_formaggi', 2, 'mozzarella', 170847, 'Mozzarella', 15, false),
('pizza_quattro_formaggi', 3, 'gorgonzola', 172175, 'Gorgonzola', 10, false),
('pizza_quattro_formaggi', 4, 'fontina', 170843, 'Fontina', 10, false),
('pizza_quattro_formaggi', 5, 'parmigiano_reggiano', 170848, 'Parmigiano Reggiano', 8, false),
('pizza_quattro_formaggi', 6, 'olive_oil', 171413, 'Olio EVO', 3, false),
('pizza_quattro_formaggi', 7, NULL, NULL, 'Acqua / brodo neutro', 4, true),
('pizza_capricciosa', 1, 'bread_white', 174925, 'Pane', 45, false),
('pizza_capricciosa', 2, 'tomatoes_canned', 170138, 'Pomodori pelati', 17, false),
('pizza_capricciosa', 3, 'mozzarella', 170847, 'Mozzarella', 15, false),
('pizza_capricciosa', 4, 'ham_cooked', 332397, 'Prosciutto cotto', 8, false),
('pizza_capricciosa', 5, 'mushrooms_white', 169251, 'Funghi champignon', 6, false),
('pizza_capricciosa', 6, 'olives_green_table', 169096, 'Olive verdi', 5, false),
('pizza_capricciosa', 7, 'olive_oil', 171413, 'Olio EVO', 3, false),
('pizza_capricciosa', 8, NULL, NULL, 'Acqua / brodo neutro', 1, true),
('pizza_fiordilatte_e_pomodorini', 1, 'bread_white', 174925, 'Pane', 48, false),
('pizza_fiordilatte_e_pomodorini', 2, 'cherry_tomato', 321360, 'Pomodorini', 20, false),
('pizza_fiordilatte_e_pomodorini', 3, 'mozzarella_whole', 170845, 'Fiordilatte', 18, false),
('pizza_fiordilatte_e_pomodorini', 4, 'parmigiano_reggiano', 170848, 'Parmigiano Reggiano', 5, false),
('pizza_fiordilatte_e_pomodorini', 5, 'olive_oil', 171413, 'Olio EVO', 4, false),
('pizza_fiordilatte_e_pomodorini', 6, NULL, NULL, 'Acqua / brodo neutro', 5, true),
('pizza_wurstel', 1, 'bread_white', 174925, 'Pane', 48, false),
('pizza_wurstel', 2, 'tomatoes_canned', 170138, 'Pomodori pelati', 18, false),
('pizza_wurstel', 3, 'mozzarella', 170847, 'Mozzarella', 16, false),
('pizza_wurstel', 4, 'wurstel', 900030134, 'Wurstel', 12, false),
('pizza_wurstel', 5, 'olive_oil', 171413, 'Olio EVO', 3, false),
('pizza_wurstel', 6, NULL, NULL, 'Acqua / brodo neutro', 3, true),
('cheeseburger_classico', 1, 'roll_hard', 175031, 'Panino (rosetta)', 35, false),
('cheeseburger_classico', 2, 'beef_ground', 174030, 'Macinato di manzo', 35, false),
('cheeseburger_classico', 3, 'cheddar', 328637, 'Cheddar', 10, false),
('cheeseburger_classico', 4, 'tomato_raw', 170457, 'Pomodori', 8, false),
('cheeseburger_classico', 5, 'lettuce_romaine', 169247, 'Lattuga romana', 5, false),
('cheeseburger_classico', 6, 'olive_oil', 171413, 'Olio EVO', 2, false),
('cheeseburger_classico', 7, NULL, NULL, 'Acqua / brodo neutro', 5, true),
('chicken_burger', 1, 'roll_hard', 175031, 'Panino (rosetta)', 35, false),
('chicken_burger', 2, 'chicken_ground', 171116, 'Macinato di pollo', 35, false),
('chicken_burger', 3, 'mozzarella', 170847, 'Mozzarella', 8, false),
('chicken_burger', 4, 'tomato_raw', 170457, 'Pomodori', 8, false),
('chicken_burger', 5, 'lettuce_romaine', 169247, 'Lattuga romana', 5, false),
('chicken_burger', 6, 'olive_oil', 171413, 'Olio EVO', 2, false),
('chicken_burger', 7, NULL, NULL, 'Acqua / brodo neutro', 7, true),
('turkey_burger', 1, 'roll_hard', 175031, 'Panino (rosetta)', 35, false),
('turkey_burger', 2, 'turkey_ground', 172850, 'Macinato di tacchino', 35, false),
('turkey_burger', 3, 'mozzarella', 170847, 'Mozzarella', 8, false),
('turkey_burger', 4, 'tomato_raw', 170457, 'Pomodori', 8, false),
('turkey_burger', 5, 'lettuce_romaine', 169247, 'Lattuga romana', 5, false),
('turkey_burger', 6, 'olive_oil', 171413, 'Olio EVO', 2, false),
('turkey_burger', 7, NULL, NULL, 'Acqua / brodo neutro', 7, true),
('hamburger_manzo_e_uovo', 1, 'roll_hard', 175031, 'Panino (rosetta)', 30, false),
('hamburger_manzo_e_uovo', 2, 'beef_ground', 174030, 'Macinato di manzo', 35, false),
('hamburger_manzo_e_uovo', 3, 'egg_whole', 171287, 'Uova', 15, false),
('hamburger_manzo_e_uovo', 4, 'cheddar', 328637, 'Cheddar', 8, false),
('hamburger_manzo_e_uovo', 5, 'tomato_raw', 170457, 'Pomodori', 5, false),
('hamburger_manzo_e_uovo', 6, 'lettuce_romaine', 169247, 'Lattuga romana', 3, false),
('hamburger_manzo_e_uovo', 7, 'olive_oil', 171413, 'Olio EVO', 1, false),
('hamburger_manzo_e_uovo', 8, NULL, NULL, 'Acqua / brodo neutro', 3, true),
('pasta_al_pomodoro', 1, 'pasta_dry', 168927, 'Pasta di semola', 58, false),
('pasta_al_pomodoro', 2, 'tomatoes_canned', 170138, 'Pomodori pelati', 32, false),
('pasta_al_pomodoro', 3, 'olive_oil', 171413, 'Olio EVO', 6, false),
('pasta_al_pomodoro', 4, 'parmigiano_reggiano', 170848, 'Parmigiano Reggiano', 4, false),
('pasta_pomodoro_e_mozzarella', 1, 'pasta_dry', 168927, 'Pasta di semola', 52, false),
('pasta_pomodoro_e_mozzarella', 2, 'tomatoes_canned', 170138, 'Pomodori pelati', 28, false),
('pasta_pomodoro_e_mozzarella', 3, 'mozzarella', 170847, 'Mozzarella', 14, false),
('pasta_pomodoro_e_mozzarella', 4, 'olive_oil', 171413, 'Olio EVO', 4, false),
('pasta_pomodoro_e_mozzarella', 5, 'parmigiano_reggiano', 170848, 'Parmigiano Reggiano', 2, false),
('pasta_zucchine_e_parmigiano', 1, 'pasta_dry', 168927, 'Pasta di semola', 55, false),
('pasta_zucchine_e_parmigiano', 2, 'zucchini_raw', 169291, 'Zucchine', 32, false),
('pasta_zucchine_e_parmigiano', 3, 'olive_oil', 171413, 'Olio EVO', 7, false),
('pasta_zucchine_e_parmigiano', 4, 'parmigiano_reggiano', 170848, 'Parmigiano Reggiano', 6, false),
('pasta_pollo_e_pomodoro', 1, 'pasta_dry', 168927, 'Pasta di semola', 47, false),
('pasta_pollo_e_pomodoro', 2, 'chicken_breast', 171077, 'Petto di pollo', 25, false),
('pasta_pollo_e_pomodoro', 3, 'tomatoes_canned', 170138, 'Pomodori pelati', 22, false),
('pasta_pollo_e_pomodoro', 4, 'olive_oil', 171413, 'Olio EVO', 6, false),
('pasta_tonno_e_olive', 1, 'pasta_dry', 168927, 'Pasta di semola', 50, false),
('pasta_tonno_e_olive', 2, 'tuna_canned_water', 171986, 'Tonno al naturale', 22, false),
('pasta_tonno_e_olive', 3, 'tomatoes_canned', 170138, 'Pomodori pelati', 18, false),
('pasta_tonno_e_olive', 4, 'olives_black_table', 169094, 'Olive nere', 5, false),
('pasta_tonno_e_olive', 5, 'olive_oil', 171413, 'Olio EVO', 5, false),
('pasta_salmone_e_zucchine', 1, 'pasta_dry', 168927, 'Pasta di semola', 48, false),
('pasta_salmone_e_zucchine', 2, 'fish_white', 175167, 'Salmone', 20, false),
('pasta_salmone_e_zucchine', 3, 'zucchini_raw', 169291, 'Zucchine', 25, false),
('pasta_salmone_e_zucchine', 4, 'olive_oil', 171413, 'Olio EVO', 5, false),
('pasta_salmone_e_zucchine', 5, 'parmigiano_reggiano', 170848, 'Parmigiano Reggiano', 2, false),
('pasta_ricotta_e_spinaci', 1, 'pasta_dry', 168927, 'Pasta di semola', 50, false),
('pasta_ricotta_e_spinaci', 2, 'cottage_cheese', 173417, 'Ricotta magra', 20, false),
('pasta_ricotta_e_spinaci', 3, 'spinach_raw', 168462, 'Spinaci', 24, false),
('pasta_ricotta_e_spinaci', 4, 'olive_oil', 171413, 'Olio EVO', 4, false),
('pasta_ricotta_e_spinaci', 5, 'parmigiano_reggiano', 170848, 'Parmigiano Reggiano', 2, false),
('pasta_alla_amatriciana', 1, 'pasta_dry', 168927, 'Pasta di semola', 52, false),
('pasta_alla_amatriciana', 2, 'tomatoes_canned', 170138, 'Pomodori pelati', 28, false),
('pasta_alla_amatriciana', 3, 'pork_belly_cured', 168277, 'Pancetta', 12, false),
('pasta_alla_amatriciana', 4, 'pecorino_romano', 171249, 'Pecorino romano', 5, false),
('pasta_alla_amatriciana', 5, 'olive_oil', 171413, 'Olio EVO', 3, false),
('pasta_melanzane_e_mozzarella', 1, 'pasta_dry', 168927, 'Pasta di semola', 48, false),
('pasta_melanzane_e_mozzarella', 2, 'eggplant', 2685577, 'Melanzane', 26, false),
('pasta_melanzane_e_mozzarella', 3, 'tomatoes_canned', 170138, 'Pomodori pelati', 14, false),
('pasta_melanzane_e_mozzarella', 4, 'mozzarella', 170847, 'Mozzarella', 8, false),
('pasta_melanzane_e_mozzarella', 5, 'olive_oil', 171413, 'Olio EVO', 4, false),
('pasta_gamberi_e_zucchine', 1, 'pasta_dry', 168927, 'Pasta di semola', 50, false),
('pasta_gamberi_e_zucchine', 2, 'shrimp', 175180, 'Gamberi', 20, false),
('pasta_gamberi_e_zucchine', 3, 'zucchini_raw', 169291, 'Zucchine', 24, false),
('pasta_gamberi_e_zucchine', 4, 'olive_oil', 171413, 'Olio EVO', 6, false),
('riso_pollo_e_zucchine', 1, 'rice_dry', 169756, 'Riso', 50, false),
('riso_pollo_e_zucchine', 2, 'chicken_breast', 171077, 'Petto di pollo', 24, false),
('riso_pollo_e_zucchine', 3, 'zucchini_raw', 169291, 'Zucchine', 20, false),
('riso_pollo_e_zucchine', 4, 'olive_oil', 171413, 'Olio EVO', 6, false),
('riso_tacchino_e_carote', 1, 'rice_dry', 169756, 'Riso', 50, false),
('riso_tacchino_e_carote', 2, 'turkey_breast', 171098, 'Petto di tacchino', 24, false),
('riso_tacchino_e_carote', 3, 'carrot_raw', 170393, 'Carote', 20, false),
('riso_tacchino_e_carote', 4, 'olive_oil', 171413, 'Olio EVO', 6, false),
('riso_tonno_e_pomodoro', 1, 'rice_dry', 169756, 'Riso', 53, false),
('riso_tonno_e_pomodoro', 2, 'tuna_canned_water', 171986, 'Tonno al naturale', 22, false),
('riso_tonno_e_pomodoro', 3, 'tomato_raw', 170457, 'Pomodori', 20, false),
('riso_tonno_e_pomodoro', 4, 'olive_oil', 171413, 'Olio EVO', 5, false),
('risotto_alle_zucchine', 1, 'rice_arborio', 168931, 'Riso Arborio', 55, false),
('risotto_alle_zucchine', 2, 'zucchini_raw', 169291, 'Zucchine', 30, false),
('risotto_alle_zucchine', 3, 'parmigiano_reggiano', 170848, 'Parmigiano Reggiano', 7, false),
('risotto_alle_zucchine', 4, 'olive_oil', 171413, 'Olio EVO', 5, false),
('risotto_alle_zucchine', 5, 'onion', 170000, 'Cipolla', 3, false),
('risotto_ai_funghi', 1, 'rice_arborio', 168931, 'Riso Arborio', 55, false),
('risotto_ai_funghi', 2, 'mushrooms_white', 169251, 'Funghi champignon', 30, false),
('risotto_ai_funghi', 3, 'parmigiano_reggiano', 170848, 'Parmigiano Reggiano', 7, false),
('risotto_ai_funghi', 4, 'olive_oil', 171413, 'Olio EVO', 5, false),
('risotto_ai_funghi', 5, 'onion', 170000, 'Cipolla', 3, false),
('risotto_gamberi_e_zucchine', 1, 'rice_arborio', 168931, 'Riso Arborio', 48, false),
('risotto_gamberi_e_zucchine', 2, 'shrimp', 175180, 'Gamberi', 18, false),
('risotto_gamberi_e_zucchine', 3, 'zucchini_raw', 169291, 'Zucchine', 25, false),
('risotto_gamberi_e_zucchine', 4, 'parmigiano_reggiano', 170848, 'Parmigiano Reggiano', 4, false),
('risotto_gamberi_e_zucchine', 5, 'olive_oil', 171413, 'Olio EVO', 5, false),
('risotto_salmone_e_zucchine', 1, 'rice_arborio', 168931, 'Riso Arborio', 48, false),
('risotto_salmone_e_zucchine', 2, 'fish_white', 175167, 'Salmone', 18, false),
('risotto_salmone_e_zucchine', 3, 'zucchini_raw', 169291, 'Zucchine', 25, false),
('risotto_salmone_e_zucchine', 4, 'parmigiano_reggiano', 170848, 'Parmigiano Reggiano', 4, false),
('risotto_salmone_e_zucchine', 5, 'olive_oil', 171413, 'Olio EVO', 5, false),
('riso_piselli_e_parmigiano', 1, 'rice_dry', 169756, 'Riso', 56, false),
('riso_piselli_e_parmigiano', 2, 'peas_green', 170419, 'Piselli', 28, false),
('riso_piselli_e_parmigiano', 3, 'parmigiano_reggiano', 170848, 'Parmigiano Reggiano', 8, false),
('riso_piselli_e_parmigiano', 4, 'olive_oil', 171413, 'Olio EVO', 5, false),
('riso_piselli_e_parmigiano', 5, 'onion', 170000, 'Cipolla', 3, false),
('cous_cous_pollo_e_verdure', 1, 'couscous', 169700, 'Cous cous', 50, false),
('cous_cous_pollo_e_verdure', 2, 'chicken_breast', 171077, 'Petto di pollo', 22, false),
('cous_cous_pollo_e_verdure', 3, 'zucchini_raw', 169291, 'Zucchine', 10, false),
('cous_cous_pollo_e_verdure', 4, 'bell_pepper_red', 170108, 'Peperoni', 8, false),
('cous_cous_pollo_e_verdure', 5, 'carrot_raw', 170393, 'Carote', 5, false),
('cous_cous_pollo_e_verdure', 6, 'olive_oil', 171413, 'Olio EVO', 5, false),
('farro_tonno_e_pomodorini', 1, 'farro_dry', 169746, 'Farro', 55, false),
('farro_tonno_e_pomodorini', 2, 'tuna_canned_water', 171986, 'Tonno al naturale', 20, false),
('farro_tonno_e_pomodorini', 3, 'cherry_tomato', 321360, 'Pomodorini', 18, false),
('farro_tonno_e_pomodorini', 4, 'olive_oil', 171413, 'Olio EVO', 5, false),
('farro_tonno_e_pomodorini', 5, 'olives_black_table', 169094, 'Olive nere', 2, false),
('lasagne_alle_verdure', 1, 'pasta_egg', 169731, 'Pasta all''uovo', 42, false),
('lasagne_alle_verdure', 2, 'zucchini_raw', 169291, 'Zucchine', 15, false),
('lasagne_alle_verdure', 3, 'eggplant', 2685577, 'Melanzane', 12, false),
('lasagne_alle_verdure', 4, 'tomatoes_canned', 170138, 'Pomodori pelati', 12, false),
('lasagne_alle_verdure', 5, 'mozzarella', 170847, 'Mozzarella', 10, false),
('lasagne_alle_verdure', 6, 'parmigiano_reggiano', 170848, 'Parmigiano Reggiano', 4, false),
('lasagne_alle_verdure', 7, 'olive_oil', 171413, 'Olio EVO', 5, false),
('lasagne_ricotta_e_spinaci', 1, 'pasta_egg', 169731, 'Pasta all''uovo', 42, false),
('lasagne_ricotta_e_spinaci', 2, 'cottage_cheese', 173417, 'Ricotta magra', 24, false),
('lasagne_ricotta_e_spinaci', 3, 'spinach_raw', 168462, 'Spinaci', 20, false),
('lasagne_ricotta_e_spinaci', 4, 'mozzarella', 170847, 'Mozzarella', 6, false),
('lasagne_ricotta_e_spinaci', 5, 'parmigiano_reggiano', 170848, 'Parmigiano Reggiano', 4, false),
('lasagne_ricotta_e_spinaci', 6, 'olive_oil', 171413, 'Olio EVO', 4, false),
('lasagne_salmone_e_zucchine', 1, 'pasta_egg', 169731, 'Pasta all''uovo', 40, false),
('lasagne_salmone_e_zucchine', 2, 'fish_white', 175167, 'Salmone', 18, false),
('lasagne_salmone_e_zucchine', 3, 'zucchini_raw', 169291, 'Zucchine', 22, false),
('lasagne_salmone_e_zucchine', 4, 'mozzarella', 170847, 'Mozzarella', 10, false),
('lasagne_salmone_e_zucchine', 5, 'parmigiano_reggiano', 170848, 'Parmigiano Reggiano', 4, false),
('lasagne_salmone_e_zucchine', 6, 'olive_oil', 171413, 'Olio EVO', 6, false),
('lasagne_pollo_e_spinaci', 1, 'pasta_egg', 169731, 'Pasta all''uovo', 40, false),
('lasagne_pollo_e_spinaci', 2, 'chicken_breast', 171077, 'Petto di pollo', 20, false),
('lasagne_pollo_e_spinaci', 3, 'spinach_raw', 168462, 'Spinaci', 20, false),
('lasagne_pollo_e_spinaci', 4, 'mozzarella', 170847, 'Mozzarella', 10, false),
('lasagne_pollo_e_spinaci', 5, 'parmigiano_reggiano', 170848, 'Parmigiano Reggiano', 4, false),
('lasagne_pollo_e_spinaci', 6, 'olive_oil', 171413, 'Olio EVO', 6, false),
('crespelle_prosciutto_e_mozzarella', 1, 'pancakes_plain', 175009, 'Pancake', 45, false),
('crespelle_prosciutto_e_mozzarella', 2, 'ham_cooked', 332397, 'Prosciutto cotto', 22, false),
('crespelle_prosciutto_e_mozzarella', 3, 'mozzarella', 170847, 'Mozzarella', 18, false),
('crespelle_prosciutto_e_mozzarella', 4, 'tomatoes_canned', 170138, 'Pomodori pelati', 8, false),
('crespelle_prosciutto_e_mozzarella', 5, 'parmigiano_reggiano', 170848, 'Parmigiano Reggiano', 4, false),
('crespelle_prosciutto_e_mozzarella', 6, 'olive_oil', 171413, 'Olio EVO', 3, false),
('crespelle_ricotta_e_spinaci', 1, 'pancakes_plain', 175009, 'Pancake', 45, false),
('crespelle_ricotta_e_spinaci', 2, 'cottage_cheese', 173417, 'Ricotta magra', 24, false),
('crespelle_ricotta_e_spinaci', 3, 'spinach_raw', 168462, 'Spinaci', 20, false),
('crespelle_ricotta_e_spinaci', 4, 'parmigiano_reggiano', 170848, 'Parmigiano Reggiano', 6, false),
('crespelle_ricotta_e_spinaci', 5, 'olive_oil', 171413, 'Olio EVO', 5, false),
('crespelle_pollo_e_zucchine', 1, 'pancakes_plain', 175009, 'Pancake', 42, false),
('crespelle_pollo_e_zucchine', 2, 'chicken_breast', 171077, 'Petto di pollo', 22, false),
('crespelle_pollo_e_zucchine', 3, 'zucchini_raw', 169291, 'Zucchine', 22, false),
('crespelle_pollo_e_zucchine', 4, 'mozzarella', 170847, 'Mozzarella', 8, false),
('crespelle_pollo_e_zucchine', 5, 'olive_oil', 171413, 'Olio EVO', 6, false),
('crespelle_salmone_e_zucchine', 1, 'pancakes_plain', 175009, 'Pancake', 42, false),
('crespelle_salmone_e_zucchine', 2, 'fish_white', 175167, 'Salmone', 20, false),
('crespelle_salmone_e_zucchine', 3, 'zucchini_raw', 169291, 'Zucchine', 23, false),
('crespelle_salmone_e_zucchine', 4, 'mozzarella', 170847, 'Mozzarella', 8, false),
('crespelle_salmone_e_zucchine', 5, 'olive_oil', 171413, 'Olio EVO', 7, false),
('pollo_alla_pizzaiola', 1, 'chicken_breast', 171077, 'Petto di pollo', 55, false),
('pollo_alla_pizzaiola', 2, 'tomatoes_canned', 170138, 'Pomodori pelati', 30, false),
('pollo_alla_pizzaiola', 3, 'mozzarella', 170847, 'Mozzarella', 8, false),
('pollo_alla_pizzaiola', 4, 'olive_oil', 171413, 'Olio EVO', 5, false),
('pollo_alla_pizzaiola', 5, 'parmigiano_reggiano', 170848, 'Parmigiano Reggiano', 2, false),
('pollo_con_zucchine', 1, 'chicken_breast', 171077, 'Petto di pollo', 60, false),
('pollo_con_zucchine', 2, 'zucchini_raw', 169291, 'Zucchine', 32, false),
('pollo_con_zucchine', 3, 'olive_oil', 171413, 'Olio EVO', 8, false),
('tacchino_con_carote', 1, 'turkey_breast', 171098, 'Petto di tacchino', 60, false),
('tacchino_con_carote', 2, 'carrot_raw', 170393, 'Carote', 32, false),
('tacchino_con_carote', 3, 'olive_oil', 171413, 'Olio EVO', 8, false),
('tacchino_alla_pizzaiola', 1, 'turkey_breast', 171098, 'Petto di tacchino', 55, false),
('tacchino_alla_pizzaiola', 2, 'tomatoes_canned', 170138, 'Pomodori pelati', 32, false),
('tacchino_alla_pizzaiola', 3, 'mozzarella', 170847, 'Mozzarella', 7, false),
('tacchino_alla_pizzaiola', 4, 'olive_oil', 171413, 'Olio EVO', 6, false),
('straccetti_di_manzo_con_rucola_e_parmigiano', 1, 'beef_lean', 168608, 'Manzo magro', 65, false),
('straccetti_di_manzo_con_rucola_e_parmigiano', 2, 'arugula_raw', 169387, 'Rucola', 20, false),
('straccetti_di_manzo_con_rucola_e_parmigiano', 3, 'parmigiano_reggiano', 170848, 'Parmigiano Reggiano', 7, false),
('straccetti_di_manzo_con_rucola_e_parmigiano', 4, 'olive_oil', 171413, 'Olio EVO', 8, false),
('polpette_di_manzo_al_pomodoro', 1, 'beef_ground', 174030, 'Macinato di manzo', 52, false),
('polpette_di_manzo_al_pomodoro', 2, 'tomatoes_canned', 170138, 'Pomodori pelati', 30, false),
('polpette_di_manzo_al_pomodoro', 3, 'bread_white', 174925, 'Pane', 10, false),
('polpette_di_manzo_al_pomodoro', 4, 'egg_whole', 171287, 'Uova', 4, false),
('polpette_di_manzo_al_pomodoro', 5, 'olive_oil', 171413, 'Olio EVO', 4, false),
('polpettone_di_tacchino_e_spinaci', 1, 'turkey_breast', 171098, 'Petto di tacchino', 55, false),
('polpettone_di_tacchino_e_spinaci', 2, 'spinach_raw', 168462, 'Spinaci', 22, false),
('polpettone_di_tacchino_e_spinaci', 3, 'bread_white', 174925, 'Pane', 10, false),
('polpettone_di_tacchino_e_spinaci', 4, 'egg_whole', 171287, 'Uova', 6, false),
('polpettone_di_tacchino_e_spinaci', 5, 'parmigiano_reggiano', 170848, 'Parmigiano Reggiano', 3, false),
('polpettone_di_tacchino_e_spinaci', 6, 'olive_oil', 171413, 'Olio EVO', 4, false),
('pollo_al_forno_con_patate', 1, 'chicken_breast', 171077, 'Petto di pollo', 48, false),
('pollo_al_forno_con_patate', 2, 'potato_cooked', 170093, 'Patate', 42, false),
('pollo_al_forno_con_patate', 3, 'olive_oil', 171413, 'Olio EVO', 10, false),
('salmone_al_forno_con_zucchine', 1, 'fish_white', 175167, 'Salmone', 58, false),
('salmone_al_forno_con_zucchine', 2, 'zucchini_raw', 169291, 'Zucchine', 34, false),
('salmone_al_forno_con_zucchine', 3, 'olive_oil', 171413, 'Olio EVO', 8, false),
('merluzzo_al_pomodoro', 1, 'cod_raw', 171955, 'Merluzzo', 62, false),
('merluzzo_al_pomodoro', 2, 'tomatoes_canned', 170138, 'Pomodori pelati', 30, false),
('merluzzo_al_pomodoro', 3, 'olive_oil', 171413, 'Olio EVO', 8, false),
('merluzzo_con_patate_e_pomodori', 1, 'cod_raw', 171955, 'Merluzzo', 42, false),
('merluzzo_con_patate_e_pomodori', 2, 'potato_cooked', 170093, 'Patate', 35, false),
('merluzzo_con_patate_e_pomodori', 3, 'tomato_raw', 170457, 'Pomodori', 15, false),
('merluzzo_con_patate_e_pomodori', 4, 'olive_oil', 171413, 'Olio EVO', 8, false),
('branzino_al_forno_con_pomodorini', 1, 'sea_bass', 175142, 'Branzino', 62, false),
('branzino_al_forno_con_pomodorini', 2, 'cherry_tomato', 321360, 'Pomodorini', 30, false),
('branzino_al_forno_con_pomodorini', 3, 'olive_oil', 171413, 'Olio EVO', 8, false),
('orata_con_patate', 1, 'gilthead_seabream', 900026088, 'Orata', 52, false),
('orata_con_patate', 2, 'potato_cooked', 170093, 'Patate', 40, false),
('orata_con_patate', 3, 'olive_oil', 171413, 'Olio EVO', 8, false),
('tonno_con_pomodori_e_olive', 1, 'tuna_canned_water', 171986, 'Tonno al naturale', 58, false),
('tonno_con_pomodori_e_olive', 2, 'tomato_raw', 170457, 'Pomodori', 28, false),
('tonno_con_pomodori_e_olive', 3, 'olives_black_table', 169094, 'Olive nere', 7, false),
('tonno_con_pomodori_e_olive', 4, 'olive_oil', 171413, 'Olio EVO', 7, false),
('gamberi_con_riso_e_zucchine', 1, 'shrimp', 175180, 'Gamberi', 25, false),
('gamberi_con_riso_e_zucchine', 2, 'rice_dry', 169756, 'Riso', 45, false),
('gamberi_con_riso_e_zucchine', 3, 'zucchini_raw', 169291, 'Zucchine', 24, false),
('gamberi_con_riso_e_zucchine', 4, 'olive_oil', 171413, 'Olio EVO', 6, false),
('cozze_al_pomodoro_con_pane', 1, 'mussels', 174216, 'Cozze', 45, false),
('cozze_al_pomodoro_con_pane', 2, 'tomatoes_canned', 170138, 'Pomodori pelati', 30, false),
('cozze_al_pomodoro_con_pane', 3, 'bread_white', 174925, 'Pane', 18, false),
('cozze_al_pomodoro_con_pane', 4, 'olive_oil', 171413, 'Olio EVO', 7, false),
('shake_whey_ultrafiltrate_e_mandorla', 1, 'whey_protein_ultrafiltered', 910000002, 'Proteine whey ultrafiltrate (generiche USDA)', 10.71, false),
('shake_whey_ultrafiltrate_e_mandorla', 2, 'almond_drink_unsweetened', 910000001, 'Bevanda di mandorla senza zuccheri', 89.29, false),
('shake_whey_ultrafiltrate_soia_e_banana', 1, 'whey_protein_ultrafiltered', 910000002, 'Proteine whey ultrafiltrate (generiche USDA)', 7.89, false),
('shake_whey_ultrafiltrate_soia_e_banana', 2, 'soymilk', 172446, 'Latte di soia', 65.79, false),
('shake_whey_ultrafiltrate_soia_e_banana', 3, 'banana', 173944, 'Banana', 26.32, false),
('shake_whey_e_latte_scremato', 1, 'whey_protein_powder', 910000003, 'Proteine whey in polvere (generiche USDA)', 10.71, false),
('shake_whey_e_latte_scremato', 2, 'milk_skim', 746776, 'Latte scremato', 89.29, false),
('crema_caseina_e_yogurt_bianco', 1, 'casein_micellar', 910000005, 'Caseina micellare in polvere (profilo EMPATHY generico)', 11.11, false),
('crema_caseina_e_yogurt_bianco', 2, 'yogurt_plain', 171284, 'Yogurt bianco', 88.89, false),
('shake_caseina_e_latte_parzialmente_scremato', 1, 'casein_micellar', 910000005, 'Caseina micellare in polvere (profilo EMPATHY generico)', 10.71, false),
('shake_caseina_e_latte_parzialmente_scremato', 2, 'milk_semi_skimmed', 746778, 'Latte parzialmente scremato', 89.29, false),
('shake_proteine_vegetali_e_mandorla', 1, 'soy_protein_powder', 910000004, 'Proteine vegetali di soia in polvere (generiche USDA)', 10.71, false),
('shake_proteine_vegetali_e_mandorla', 2, 'almond_drink_unsweetened', 910000001, 'Bevanda di mandorla senza zuccheri', 89.29, false),
('shake_proteine_vegetali_e_soia', 1, 'soy_protein_powder', 910000004, 'Proteine vegetali di soia in polvere (generiche USDA)', 10.71, false),
('shake_proteine_vegetali_e_soia', 2, 'soymilk', 172446, 'Latte di soia', 89.29, false),
('shake_whey_banana_e_burro_di_arachidi', 1, 'whey_protein_ultrafiltered', 910000002, 'Proteine whey ultrafiltrate (generiche USDA)', 8.22, false),
('shake_whey_banana_e_burro_di_arachidi', 2, 'almond_drink_unsweetened', 910000001, 'Bevanda di mandorla senza zuccheri', 60.27, false),
('shake_whey_banana_e_burro_di_arachidi', 3, 'banana', 173944, 'Banana', 27.4, false),
('shake_whey_banana_e_burro_di_arachidi', 4, 'peanut_butter', 2262072, 'Burro di arachidi', 4.11, false)
) as v (recipe_key, position, canonical_key, fdc_id, label_it, grams_per_100g, is_neutral)
join public.nutrition_recipes r on r.recipe_key = v.recipe_key;

-- CONTROLLO (eseguire dopo l'apply; atteso: recipes = 82 attive tutte con tier not null e
-- source_version 'mario_v9'; componenti = 405; meals: 71 lunch+dinner, 3 breakfast,
-- 8 breakfast+snack; review = 2; famiglie con tetto: LASAGNE 5, CRESPELLE 4, PIZZA 12, BURGER 5):
--   select count(*) as recipes,
--          count(*) filter (where tier is null) as senza_tier,
--          count(*) filter (where source_version <> 'mario_v9') as non_v9,
--          count(*) filter (where meals = '["lunch","dinner"]'::jsonb) as lunch_dinner,
--          count(*) filter (where meals = '["breakfast"]'::jsonb) as breakfast,
--          count(*) filter (where meals = '["breakfast","snack"]'::jsonb) as breakfast_snack,
--          count(*) filter (where note like 'REVIEW (P06)%') as review
--   from public.nutrition_recipes where is_active;
--   select count(*) as componenti from public.nutrition_recipe_components;
--   select family, count(*) from public.nutrition_recipes where family in ('LASAGNE','CRESPELLE','PIZZA','BURGER') group by family;
--   select r.recipe_key, round(sum(c.grams_per_100g), 2) as tot
--   from public.nutrition_recipes r join public.nutrition_recipe_components c on c.recipe_id = r.id
--   group by r.recipe_key having sum(c.grams_per_100g) < 99 or sum(c.grams_per_100g) > 101;  -- atteso: 0 righe
