-- SEED di backup del catalogo curato nutrition_menu_foods.
-- Snapshot point-in-time del DB prod al 24 luglio 2026: 402 righe
-- (400 attive + 2 disattivate di proposito: mixed_veg, mixed_fruit).
--
-- PERCHÉ: le righe del catalogo vivono solo nel DB prod (si curano da
-- /admin/alimenti, INSERT senza deploy). Se il DB venisse ricostruito dalle
-- sole migrazioni, la tabella resterebbe vuota e il motore meal-plan V2
-- ricadrebbe in silenzio sulla allowlist hardcoded da 115 alimenti.
-- Questo file è la rete di sicurezza: ripopola il catalogo alla baseline.
--
-- PERCHÉ ON CONFLICT DO NOTHING: il DB vivo è la fonte di verità — il
-- catalogo si edita da /admin/alimenti, mai da qui. Su un DB già popolato
-- questa migrazione è un no-op totale: non sovrascrive label, pool, flag
-- o stato is_active modificati dopo lo snapshot.
--
-- REFRESH: quando il catalogo cambia molto, rigenerare questo file come
-- NUOVA migrazione con lo stesso metodo (select format('(%L, %s, %L, ...)')
-- ... order by canonical_key, a blocchi) e la stessa clausola ON CONFLICT.
-- Non modificare questo file dopo che è stato applicato.

insert into public.nutrition_menu_foods (canonical_key, fdc_id, label_it, serving_basis, pool_keys, rotation_key, carb_family, is_meat, is_fish, is_animal_product, sort_priority, is_active) values
('alfalfa_sprouts', 168384, 'Germogli di erba medica', 'dry_grams', '{lunch_veg,dinner_veg}', 'veg:germogli', NULL, 'f', 'f', 'f', 300, 't'),
('almond_butter', 168588, 'Burro di mandorle', 'dry_grams', '{breakfast_fat}', 'fat:mandorla', NULL, 'f', 'f', 'f', 200, 't'),
('almonds_raw', 2346393, 'Mandorle', 'dry_grams', '{breakfast_fat,snack_pro}', NULL, NULL, 'f', 'f', 'f', 100, 't'),
('amaranth', 170682, 'Amaranto', 'dry_grams', '{lunch_carb,dinner_carb}', 'carb:amaranto', 'carb_starch', 'f', 'f', 'f', 300, 't'),
('amberjack', 175163, 'Ricciola', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:ricciola', NULL, 'f', 't', 'f', 200, 't'),
('anchovy', 174182, 'Acciughe', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:acciughe', NULL, 'f', 't', 'f', 100, 't'),
('anchovy_oil', 174183, 'Filetti di acciughe sott''olio', 'cooked_grams', '{lunch_pro,dinner_pro}', 'anchovy', NULL, 'f', 't', 'f', 150, 't'),
('apple_fuji', 167793, 'Mela Fuji', 'dry_grams', '{snack_cho}', 'cho:mela', NULL, 'f', 'f', 'f', 150, 't'),
('apple_gala', 168204, 'Mela Gala', 'dry_grams', '{snack_cho}', 'cho:mela', NULL, 'f', 'f', 'f', 150, 't'),
('apple_golden', 168202, 'Mela Golden', 'dry_grams', '{snack_cho}', 'cho:mela', NULL, 'f', 'f', 'f', 150, 't'),
('apple_granny_smith', 168203, 'Mela Granny Smith', 'dry_grams', '{snack_cho}', 'cho:mela', NULL, 'f', 'f', 'f', 200, 't'),
('apple_raw', 1750340, 'Mela', 'dry_grams', '{snack_cho}', NULL, NULL, 'f', 'f', 'f', 100, 't'),
('apple_red_delicious', 168201, 'Mela Red Delicious', 'dry_grams', '{snack_cho}', 'cho:mela', NULL, 'f', 'f', 'f', 200, 't'),
('apples_dried', 171691, 'Mela essiccata', 'dry_grams', '{snack_cho}', 'cho:mela', NULL, 'f', 'f', 'f', 300, 't'),
('apricot', 171697, 'Albicocche', 'dry_grams', '{snack_cho}', NULL, NULL, 'f', 'f', 'f', 100, 't'),
('apricots_dried', 173941, 'Albicocche secche', 'dry_grams', '{snack_cho}', 'cho:albicocche', NULL, 'f', 'f', 'f', 200, 't'),
('artichoke', 169205, 'Carciofi', 'dry_grams', '{lunch_veg,dinner_veg}', NULL, NULL, 'f', 'f', 'f', 100, 't'),
('arugula_raw', 169387, 'Rucola', 'dry_grams', '{lunch_veg,dinner_veg}', NULL, NULL, 'f', 'f', 'f', 150, 't'),
('asparagus_raw', 168389, 'Asparagi', 'dry_grams', '{lunch_veg,dinner_veg}', NULL, NULL, 'f', 'f', 'f', 150, 't'),
('avocado', 171705, 'Avocado', 'dry_grams', '{breakfast_fat}', NULL, NULL, 'f', 'f', 'f', 100, 't'),
('bagel_plain', 174899, 'Bagel', 'dry_grams', '{breakfast_cho}', 'breakfast:bagel', NULL, 'f', 'f', 'f', 100, 't'),
('banana', 173944, 'Banana', 'dry_grams', '{snack_cho}', NULL, NULL, 'f', 'f', 'f', 100, 't'),
('banana_dried', 173945, 'Banana essiccata', 'dry_grams', '{snack_cho}', 'cho:banana', NULL, 'f', 'f', 'f', 200, 't'),
('barley_hulled', 170283, 'Orzo decorticato', 'dry_grams', '{lunch_carb,dinner_carb}', 'carb:orzo', 'carb_starch', 'f', 'f', 'f', 300, 't'),
('barley_pearled', 170285, 'Orzo perlato', 'cooked_grams', '{lunch_carb,dinner_carb}', 'carb:orzo', 'carb_starch', 'f', 'f', 'f', 150, 't'),
('beans_black', 173735, 'Fagioli neri', 'cooked_grams', '{lunch_pro,dinner_pro}', 'prot:fagioli', NULL, 'f', 'f', 'f', 200, 't'),
('beans_cranberry', 173736, 'Fagioli borlotti', 'cooked_grams', '{lunch_pro,dinner_pro}', 'prot:fagioli', NULL, 'f', 'f', 'f', 100, 't'),
('beans_kidney', 175242, 'Fagioli rossi', 'cooked_grams', '{lunch_pro,dinner_pro}', 'prot:fagioli', NULL, 'f', 'f', 'f', 150, 't'),
('beans_white', 175249, 'Fagioli cannellini', 'cooked_grams', '{lunch_pro,dinner_pro}', 'prot:fagioli', NULL, 'f', 'f', 'f', 150, 't'),
('beef_brisket', 170210, 'Punta di petto di manzo', 'cooked_grams', '{lunch_pro,dinner_pro}', 'prot:manzo', NULL, 't', 'f', 'f', 200, 't'),
('beef_eye_round', 746760, 'Girello di manzo', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:manzo', NULL, 't', 'f', 'f', 200, 't'),
('beef_ground', 174030, 'Macinato di manzo', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:manzo', NULL, 't', 'f', 'f', 100, 't'),
('beef_lean', 168608, 'Manzo magro', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:manzo', NULL, 't', 'f', 'f', 100, 't'),
('beef_liver', 169451, 'Fegato di manzo', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:fegato', NULL, 't', 'f', 'f', 300, 't'),
('beef_ribeye', 172164, 'Costata di manzo', 'cooked_grams', '{lunch_pro,dinner_pro}', 'prot:manzo', NULL, 't', 'f', 'f', 150, 't'),
('beef_shank', 169442, 'Ossobuco di manzo', 'cooked_grams', '{lunch_pro,dinner_pro}', 'prot:manzo', NULL, 't', 'f', 'f', 200, 't'),
('beef_sirloin', 2727574, 'Controfiletto di manzo', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:manzo', NULL, 't', 'f', 'f', 200, 't'),
('beef_stew', 171206, 'Spezzatino di manzo', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:manzo', NULL, 't', 'f', 'f', 200, 't'),
('beef_tbone', 169464, 'Fiorentina (bistecca con osso)', 'cooked_grams', '{lunch_pro,dinner_pro}', 'prot:manzo', NULL, 't', 'f', 'f', 200, 't'),
('beef_tenderloin', 171767, 'Filetto di manzo', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:manzo', NULL, 't', 'f', 'f', 150, 't'),
('beef_top_round', 2646173, 'Fesa di manzo', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:manzo', NULL, 't', 'f', 'f', 150, 't'),
('beet_greens', 2747653, 'Foglie di barbabietola', 'dry_grams', '{lunch_veg,dinner_veg}', NULL, NULL, 'f', 'f', 'f', 200, 't'),
('beetroot', 2685576, 'Barbabietola', 'dry_grams', '{lunch_veg,dinner_veg}', NULL, NULL, 'f', 'f', 'f', 200, 't'),
('bell_pepper_green', 170427, 'Peperoni verdi', 'dry_grams', '{lunch_veg,dinner_veg}', 'veg:peperoni', NULL, 'f', 'f', 'f', 200, 't'),
('bell_pepper_red', 170108, 'Peperoni', 'dry_grams', '{lunch_veg,dinner_veg}', NULL, NULL, 'f', 'f', 'f', 150, 't'),
('bell_pepper_yellow', 169383, 'Peperoni gialli', 'dry_grams', '{lunch_veg,dinner_veg}', 'veg:peperoni', NULL, 'f', 'f', 'f', 200, 't'),
('black_eyed_peas', 173759, 'Fagioli dall''occhio', 'cooked_grams', '{lunch_pro,dinner_pro}', 'prot:fagioli', NULL, 'f', 'f', 'f', 200, 't'),
('blackberries', 173946, 'More', 'dry_grams', '{snack_cho}', NULL, NULL, 'f', 'f', 'f', 200, 't'),
('blueberries_raw', 2346411, 'Mirtilli', 'dry_grams', '{snack_cho}', NULL, NULL, 'f', 'f', 'f', 100, 't'),
('bok_choy', 2685572, 'Pak choi', 'dry_grams', '{lunch_veg,dinner_veg}', NULL, NULL, 'f', 'f', 'f', 300, 't'),
('borage', 170481, 'Borragine', 'dry_grams', '{lunch_veg,dinner_veg}', NULL, NULL, 'f', 'f', 'f', 300, 't'),
('brazil_nuts', 2515373, 'Noci del Brasile', 'dry_grams', '{breakfast_fat}', NULL, NULL, 'f', 'f', 'f', 300, 't'),
('bread_multigrain', 168013, 'Pane multicereale', 'dry_grams', '{breakfast_cho}', 'breakfast:bread', NULL, 'f', 'f', 'f', 150, 't'),
('bread_oatmeal', 172678, 'Pane d''avena', 'dry_grams', '{breakfast_cho}', 'breakfast:bread', NULL, 'f', 'f', 'f', 200, 't'),
('bread_pita', 174915, 'Pane pita', 'dry_grams', '{breakfast_cho}', 'breakfast:bread', NULL, 'f', 'f', 'f', 200, 't'),
('bread_raisin', 172680, 'Pane all''uvetta', 'dry_grams', '{breakfast_cho}', NULL, NULL, 'f', 'f', 'f', 300, 't'),
('bread_rye', 172684, 'Pane di segale', 'dry_grams', '{breakfast_cho}', 'breakfast:bread', NULL, 'f', 'f', 'f', 100, 't'),
('bread_white', 174925, 'Pane', 'dry_grams', '{breakfast_cho}', 'breakfast:bread', NULL, 'f', 'f', 'f', 100, 't'),
('bread_whole_wheat', 172690, 'Pane integrale', 'dry_grams', '{breakfast_cho}', 'breakfast:bread', NULL, 'f', 'f', 'f', 100, 't'),
('breadsticks', 174929, 'Grissini', 'dry_grams', '{breakfast_cho}', NULL, NULL, 'f', 'f', 'f', 200, 't'),
('bresaola', 170604, 'Bresaola', 'dry_grams', '{lunch_pro,dinner_pro,snack_pro}', NULL, NULL, 't', 'f', 'f', 150, 't'),
('brie', 172177, 'Brie', 'dry_grams', '{lunch_pro,dinner_pro,snack_pro}', 'prot:formaggio_stagionato', NULL, 'f', 'f', 't', 300, 't'),
('broccoli_raab', 170381, 'Cime di rapa', 'dry_grams', '{lunch_veg,dinner_veg}', NULL, NULL, 'f', 'f', 'f', 100, 't'),
('broccoli_raw', 170379, 'Broccoli', 'dry_grams', '{lunch_veg,dinner_veg}', NULL, NULL, 'f', 'f', 'f', 100, 't'),
('brussels_sprouts', 2685575, 'Cavolini di Bruxelles', 'dry_grams', '{lunch_veg,dinner_veg}', NULL, NULL, 'f', 'f', 'f', 150, 't'),
('buckwheat', 2512378, 'Grano saraceno', 'dry_grams', '{lunch_carb,dinner_carb}', 'carb:grano_saraceno', 'carb_starch', 'f', 'f', 'f', 150, 't'),
('bulgur', 170287, 'Bulgur', 'cooked_grams', '{lunch_carb,dinner_carb}', 'carb:bulgur', 'carb_starch', 'f', 'f', 'f', 150, 't'),
('butter_unsalted', 173430, 'Burro', 'dry_grams', '{breakfast_fat}', 'fat:burro', NULL, 'f', 'f', 't', 150, 't'),
('buttermilk', 2259792, 'Latticello', 'ml', '{breakfast_pro}', 'breakfast:latte', NULL, 'f', 'f', 't', 300, 't'),
('butternut_squash', 2685570, 'Zucca', 'dry_grams', '{lunch_veg,dinner_veg}', NULL, NULL, 'f', 'f', 'f', 150, 't'),
('cabbage_green', 2346407, 'Cavolo cappuccio', 'dry_grams', '{lunch_veg,dinner_veg}', 'veg:cavoli', NULL, 'f', 'f', 'f', 200, 't'),
('cabbage_red', 2346408, 'Cavolo rosso', 'dry_grams', '{lunch_veg,dinner_veg}', 'veg:cavoli', NULL, 'f', 'f', 'f', 200, 't'),
('cabbage_savoy', 170388, 'Verza', 'dry_grams', '{lunch_veg,dinner_veg}', 'veg:cavoli', NULL, 'f', 'f', 'f', 200, 't'),
('camembert', 172178, 'Camembert', 'dry_grams', '{lunch_pro,dinner_pro,snack_pro}', NULL, NULL, 'f', 'f', 't', 200, 't'),
('cardoon', 169981, 'Cardi', 'dry_grams', '{lunch_veg,dinner_veg}', NULL, NULL, 'f', 'f', 'f', 200, 't'),
('carp', 171952, 'Carpa', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:carpa', NULL, 'f', 't', 'f', 300, 't'),
('carrot_raw', 170393, 'Carote', 'dry_grams', '{dinner_veg}', NULL, NULL, 'f', 'f', 'f', 100, 't'),
('cashew_butter', 170163, 'Crema di anacardi', 'dry_grams', '{breakfast_fat}', NULL, NULL, 'f', 'f', 'f', 300, 't'),
('cashews', 2515374, 'Anacardi', 'dry_grams', '{breakfast_fat}', NULL, NULL, 'f', 'f', 'f', 100, 't'),
('catfish', 174186, 'Pesce gatto', 'dry_grams', '{lunch_pro,dinner_pro}', NULL, NULL, 'f', 't', 'f', 200, 't'),
('cauliflower', 2685573, 'Cavolfiore', 'dry_grams', '{lunch_veg,dinner_veg}', NULL, NULL, 'f', 'f', 'f', 150, 't'),
('cauliflower_green', 169389, 'Cavolfiore verde', 'dry_grams', '{lunch_veg,dinner_veg}', 'veg:cavoli', NULL, 'f', 'f', 'f', 200, 't'),
('celeriac', 170400, 'Sedano rapa', 'dry_grams', '{lunch_veg,dinner_veg}', NULL, NULL, 'f', 'f', 'f', 200, 't'),
('celery', 169988, 'Sedano', 'dry_grams', '{lunch_veg,dinner_veg}', NULL, NULL, 'f', 'f', 'f', 100, 't'),
('cheddar', 328637, 'Cheddar', 'dry_grams', '{snack_pro,lunch_pro,dinner_pro}', NULL, NULL, 'f', 'f', 't', 200, 't'),
('cheese_hard', 171247, 'Grana Padano', 'dry_grams', '{snack_pro}', NULL, NULL, 'f', 'f', 't', 100, 't'),
('cherries', 171719, 'Ciliegie', 'dry_grams', '{snack_cho}', NULL, NULL, 'f', 'f', 'f', 100, 't'),
('cherry_tomato', 321360, 'Pomodorini', 'dry_grams', '{lunch_veg,dinner_veg}', 'veg:pomodori', NULL, 'f', 'f', 'f', 200, 't'),
('chestnuts', 170190, 'Castagne', 'cooked_grams', '{lunch_carb,dinner_carb}', 'carb:castagne', 'carb_starch', 'f', 'f', 'f', 200, 't'),
('chia_seeds', 170554, 'Semi di chia', 'dry_grams', '{breakfast_fat}', NULL, NULL, 'f', 'f', 'f', 100, 't'),
('chicken_breast', 171077, 'Petto di pollo', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:pollo', NULL, 't', 'f', 'f', 100, 't'),
('chicken_drumstick', 173614, 'Fuso di pollo', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:pollo_altri', NULL, 't', 'f', 'f', 200, 't'),
('chicken_ground', 171116, 'Macinato di pollo', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:pollo_altri', NULL, 't', 'f', 'f', 200, 't'),
('chicken_liver', 171060, 'Fegatini di pollo', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:fegato', NULL, 't', 'f', 'f', 300, 't'),
('chicken_thigh', 2646171, 'Sovracoscia di pollo', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:pollo_altri', NULL, 't', 'f', 'f', 150, 't'),
('chicken_wing', 173632, 'Ali di pollo', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:pollo_altri', NULL, 't', 'f', 'f', 300, 't'),
('chickpeas_cooked', 173799, 'Ceci', 'cooked_grams', '{lunch_pro,dinner_pro}', 'prot:ceci', NULL, 'f', 'f', 'f', 150, 't'),
('chicory_greens', 169992, 'Cicoria', 'dry_grams', '{lunch_veg,dinner_veg}', 'veg:cicoria', NULL, 'f', 'f', 'f', 100, 't'),
('clams', 174214, 'Vongole', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:vongole', NULL, 'f', 't', 'f', 100, 't'),
('clementine', 168195, 'Clementine', 'dry_grams', '{snack_cho}', 'cho:agrumi', NULL, 'f', 'f', 'f', 100, 't')
on conflict (canonical_key) do nothing;

insert into public.nutrition_menu_foods (canonical_key, fdc_id, label_it, serving_basis, pool_keys, rotation_key, carb_family, is_meat, is_fish, is_animal_product, sort_priority, is_active) values
('coconut', 170169, 'Cocco', 'dry_grams', '{breakfast_fat}', NULL, NULL, 'f', 'f', 'f', 200, 't'),
('coconut_dried', 170170, 'Cocco disidratato', 'dry_grams', '{breakfast_fat}', 'fat:cocco', NULL, 'f', 'f', 'f', 300, 't'),
('coconut_milk', 170173, 'Latte di cocco', 'ml', '{breakfast_fat}', NULL, NULL, 'f', 'f', 'f', 200, 't'),
('coconut_oil', 171412, 'Olio di cocco', 'ml', '{breakfast_fat}', NULL, NULL, 'f', 'f', 'f', 200, 't'),
('cod_raw', 171955, 'Merluzzo', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:merluzzo', NULL, 'f', 't', 'f', 150, 't'),
('corn_cakes', 168857, 'Gallette di mais', 'dry_grams', '{breakfast_cho}', 'breakfast:gallette', NULL, 'f', 'f', 'f', 200, 't'),
('corn_flakes', 174648, 'Corn flakes', 'dry_grams', '{breakfast_cho}', 'breakfast:cereali', NULL, 'f', 'f', 'f', 100, 't'),
('cornmeal_polenta', 168929, 'Polenta (farina di mais)', 'dry_grams', '{lunch_carb,dinner_carb}', 'carb:polenta', 'carb_starch', 'f', 'f', 'f', 150, 't'),
('cornsalad', 169219, 'Songino', 'dry_grams', '{lunch_veg,dinner_veg}', NULL, NULL, 'f', 'f', 'f', 200, 't'),
('cottage_cheese', 173417, 'Ricotta magra', 'dry_grams', '{breakfast_pro,snack_pro}', NULL, NULL, 'f', 'f', 't', 100, 't'),
('cottage_cheese_2pct', 328841, 'Fiocchi di latte (2%)', 'cooked_grams', '{breakfast_pro,snack_pro}', NULL, NULL, 'f', 'f', 't', 200, 't'),
('cottage_creamed', 172179, 'Fiocchi di latte', 'dry_grams', '{breakfast_pro,snack_pro}', NULL, NULL, 'f', 'f', 't', 200, 't'),
('cottage_dry', 172181, 'Fiocchi di latte magri', 'dry_grams', '{breakfast_pro,snack_pro}', NULL, NULL, 'f', 'f', 't', 200, 't'),
('couscous', 169700, 'Cous cous', 'cooked_grams', '{lunch_carb,dinner_carb}', 'carb:couscous', 'carb_starch', 'f', 'f', 'f', 150, 't'),
('crab', 174204, 'Granchio', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:granchio', NULL, 'f', 't', 'f', 300, 't'),
('crackers_whole', 174985, 'Crackers integrali', 'dry_grams', '{breakfast_cho}', 'breakfast:crackers', NULL, 'f', 'f', 'f', 100, 't'),
('cranberries_dried', 171723, 'Mirtilli rossi essiccati', 'dry_grams', '{snack_cho}', NULL, NULL, 'f', 'f', 'f', 300, 't'),
('cream_cheese', 173418, 'Formaggio spalmabile', 'cooked_grams', '{breakfast_fat}', NULL, NULL, 'f', 'f', 't', 150, 't'),
('cream_cheese_light', 172207, 'Formaggio spalmabile magro', 'dry_grams', '{breakfast_pro,snack_pro}', NULL, NULL, 'f', 'f', 't', 200, 't'),
('crispbread_rye', 172739, 'Crispbread di segale', 'dry_grams', '{breakfast_cho}', 'breakfast:crackers', NULL, 'f', 'f', 'f', 300, 't'),
('croaker', 174192, 'Ombrina', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:ombrina', NULL, 'f', 't', 'f', 300, 't'),
('croissant_butter', 174987, 'Cornetto', 'cooked_grams', '{breakfast_cho}', 'breakfast:croissant', NULL, 'f', 'f', 't', 200, 't'),
('cucumber', 2346406, 'Cetrioli', 'dry_grams', '{lunch_veg,dinner_veg}', NULL, NULL, 'f', 'f', 'f', 150, 't'),
('currants', 173964, 'Ribes', 'dry_grams', '{snack_cho}', NULL, NULL, 'f', 'f', 'f', 200, 't'),
('currants_black', 173963, 'Ribes nero', 'dry_grams', '{snack_cho}', 'cho:ribes', NULL, 'f', 'f', 'f', 200, 't'),
('cuttlefish', 174215, 'Seppia', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:seppia', NULL, 'f', 't', 'f', 100, 't'),
('dandelion_greens', 169226, 'Tarassaco', 'dry_grams', '{lunch_veg,dinner_veg}', NULL, NULL, 'f', 'f', 'f', 300, 't'),
('dark_chocolate_70', 170273, 'Cioccolato fondente', 'dry_grams', '{breakfast_fat}', NULL, NULL, 'f', 'f', 'f', 100, 't'),
('dates_medjool', 168191, 'Datteri', 'dry_grams', '{snack_cho}', NULL, NULL, 'f', 'f', 'f', 100, 't'),
('duck', 172410, 'Anatra', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:anatra', NULL, 't', 'f', 'f', 300, 't'),
('edam', 173419, 'Edam', 'dry_grams', '{snack_pro,lunch_pro,dinner_pro}', NULL, NULL, 'f', 'f', 't', 300, 't'),
('edamame', 168411, 'Edamame', 'cooked_grams', '{lunch_pro,dinner_pro}', 'prot:edamame', NULL, 'f', 'f', 'f', 150, 't'),
('eel', 174193, 'Anguilla', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:anguilla', NULL, 'f', 't', 'f', 300, 't'),
('egg_boiled', 173424, 'Uovo sodo', 'cooked_grams', '{breakfast_pro,snack_pro}', 'breakfast:egg', NULL, 'f', 'f', 't', 200, 't'),
('egg_poached', 172186, 'Uovo in camicia', 'cooked_grams', '{breakfast_pro}', 'breakfast:egg', NULL, 'f', 'f', 't', 200, 't'),
('egg_scrambled', 172187, 'Uova strapazzate', 'cooked_grams', '{breakfast_pro}', 'breakfast:egg', NULL, 'f', 'f', 't', 200, 't'),
('egg_white', 172183, 'Albume d''uovo', 'dry_grams', '{breakfast_pro}', 'breakfast:egg', NULL, 'f', 'f', 't', 100, 't'),
('egg_whole', 171287, 'Uova', 'dry_grams', '{breakfast_pro,lunch_pro,snack_pro}', 'breakfast:egg', NULL, 'f', 'f', 't', 100, 't'),
('eggplant', 2685577, 'Melanzane', 'dry_grams', '{lunch_veg,dinner_veg}', NULL, NULL, 'f', 'f', 'f', 150, 't'),
('emmental', 746767, 'Emmental', 'dry_grams', '{lunch_pro,dinner_pro,snack_pro}', 'prot:formaggio_stagionato', NULL, 'f', 'f', 't', 200, 't'),
('endive_belgian', 170404, 'Indivia belga', 'dry_grams', '{lunch_veg,dinner_veg}', 'veg:cicoria', NULL, 'f', 'f', 'f', 200, 't'),
('endive_curly', 168412, 'Indivia riccia', 'dry_grams', '{lunch_veg,dinner_veg}', 'veg:indivia', NULL, 'f', 'f', 'f', 200, 't'),
('english_muffin_whole', 172762, 'Muffin inglese integrale', 'dry_grams', '{breakfast_cho}', NULL, NULL, 'f', 'f', 'f', 300, 't'),
('escarole', 168413, 'Scarola', 'cooked_grams', '{lunch_veg,dinner_veg}', 'veg:indivia', NULL, 'f', 'f', 'f', 200, 't'),
('farro_dry', 169746, 'Farro', 'dry_grams', '{lunch_carb,dinner_carb}', 'carb:farro', 'carb_starch', 'f', 'f', 'f', 100, 't'),
('fava_beans', 173753, 'Fave', 'cooked_grams', '{lunch_pro,dinner_pro}', 'prot:fave', NULL, 'f', 'f', 'f', 100, 't'),
('fennel', 2747655, 'Finocchio', 'dry_grams', '{lunch_veg,dinner_veg}', NULL, NULL, 'f', 'f', 'f', 150, 't'),
('feta', 173420, 'Feta', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:feta', NULL, 'f', 'f', 't', 150, 't'),
('figs', 173021, 'Fichi', 'dry_grams', '{snack_cho}', NULL, NULL, 'f', 'f', 'f', 100, 't'),
('figs_dried', 174665, 'Fichi secchi', 'dry_grams', '{snack_cho}', 'cho:fichi', NULL, 'f', 'f', 'f', 200, 't'),
('fish_white', 175167, 'Salmone', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:pesce', NULL, 'f', 't', 'f', 100, 't'),
('flaxseed', 169414, 'Semi di lino', 'dry_grams', '{breakfast_fat}', NULL, NULL, 'f', 'f', 'f', 100, 't'),
('focaccia', 167945, 'Focaccia', 'dry_grams', '{breakfast_cho}', 'breakfast:bread', NULL, 'f', 'f', 'f', 150, 't'),
('fontina', 170843, 'Fontina', 'dry_grams', '{lunch_pro,dinner_pro,snack_pro}', 'prot:formaggio_stagionato', NULL, 'f', 'f', 't', 200, 't'),
('ghee', 171314, 'Burro chiarificato', 'cooked_grams', '{breakfast_fat}', NULL, NULL, 'f', 'f', 't', 200, 't'),
('goat_cheese', 173435, 'Caprino', 'dry_grams', '{snack_pro,lunch_pro,dinner_pro}', 'prot:formaggio_fresco', NULL, 'f', 'f', 't', 200, 't'),
('goat_cheese_aged', 172197, 'Caprino stagionato', 'dry_grams', '{lunch_pro,dinner_pro,snack_pro}', 'prot:formaggio_stagionato', NULL, 'f', 'f', 't', 200, 't'),
('goat_milk', 171278, 'Latte di capra', 'ml', '{breakfast_pro}', 'breakfast:latte', NULL, 'f', 'f', 't', 200, 't'),
('goji_berries', 173032, 'Bacche di goji', 'dry_grams', '{snack_cho}', NULL, NULL, 'f', 'f', 'f', 300, 't'),
('goose', 172413, 'Oca', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:oca', NULL, 't', 'f', 'f', 300, 't'),
('gooseberries', 173030, 'Uva spina', 'dry_grams', '{snack_cho}', NULL, NULL, 'f', 'f', 'f', 300, 't'),
('gorgonzola', 172175, 'Gorgonzola', 'dry_grams', '{lunch_pro,dinner_pro,snack_pro}', 'prot:formaggio_stagionato', NULL, 'f', 'f', 't', 200, 't'),
('gouda', 171241, 'Gouda', 'dry_grams', '{snack_pro,lunch_pro,dinner_pro}', NULL, NULL, 'f', 'f', 't', 300, 't'),
('granola', 171646, 'Granola', 'dry_grams', '{breakfast_cho}', 'breakfast:granola', NULL, 'f', 'f', 't', 100, 't'),
('grapefruit', 173033, 'Pompelmo', 'dry_grams', '{snack_cho}', 'cho:agrumi', NULL, 'f', 'f', 'f', 200, 't'),
('grapefruit_pink', 174673, 'Pompelmo rosa', 'dry_grams', '{snack_cho}', 'cho:agrumi', NULL, 'f', 'f', 'f', 150, 't'),
('grapes', 174683, 'Uva', 'dry_grams', '{snack_cho}', NULL, NULL, 'f', 'f', 'f', 100, 't'),
('grapes_slipskin', 174682, 'Uva fragola', 'dry_grams', '{snack_cho}', 'cho:uva', NULL, 'f', 'f', 'f', 150, 't'),
('green_beans', 2346400, 'Fagiolini', 'dry_grams', '{lunch_veg,dinner_veg}', NULL, NULL, 'f', 'f', 'f', 150, 't'),
('green_beans_yellow', 169320, 'Fagiolini gialli', 'dry_grams', '{lunch_veg,dinner_veg}', 'veg:fagiolini', NULL, 'f', 'f', 'f', 200, 't'),
('grouper', 171962, 'Cernia', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:cernia', NULL, 'f', 't', 'f', 200, 't'),
('gruyere', 171242, 'Gruyère', 'dry_grams', '{lunch_pro,dinner_pro,snack_pro}', 'prot:formaggio_stagionato', NULL, 'f', 'f', 't', 200, 't'),
('guava', 173044, 'Guava', 'dry_grams', '{snack_cho}', NULL, NULL, 'f', 'f', 'f', 300, 't'),
('guinea_fowl', 174471, 'Faraona', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:faraona', NULL, 't', 'f', 'f', 300, 't'),
('haddock', 171964, 'Eglefino', 'dry_grams', '{lunch_pro,dinner_pro}', NULL, NULL, 'f', 't', 'f', 200, 't'),
('halibut', 174200, 'Halibut', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:halibut', NULL, 'f', 't', 'f', 200, 't'),
('ham_cooked', 332397, 'Prosciutto cotto', 'dry_grams', '{snack_pro}', NULL, NULL, 't', 'f', 'f', 100, 't'),
('hazelnuts', 170581, 'Nocciole', 'dry_grams', '{breakfast_fat}', NULL, NULL, 'f', 'f', 'f', 100, 't'),
('heavy_cream', 2346386, 'Panna fresca', 'ml', '{breakfast_fat}', NULL, NULL, 'f', 'f', 't', 150, 't'),
('hemp_seeds', 170148, 'Semi di canapa', 'dry_grams', '{breakfast_fat}', NULL, NULL, 'f', 'f', 'f', 300, 't'),
('herring', 175116, 'Aringa', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:aringa', NULL, 'f', 't', 'f', 300, 't'),
('herring_smoked', 173668, 'Aringa affumicata', 'cooked_grams', '{lunch_pro,dinner_pro}', 'herring', NULL, 'f', 't', 'f', 200, 't'),
('honey', 169640, 'Miele', 'cooked_grams', '{breakfast_cho}', NULL, NULL, 'f', 'f', 't', 150, 't'),
('horse_meat', 175086, 'Carne di cavallo', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:cavallo', NULL, 't', 'f', 'f', 300, 't'),
('hummus', 174289, 'Hummus', 'dry_grams', '{snack_pro}', NULL, NULL, 'f', 'f', 'f', 100, 't'),
('jam_apricot', 170645, 'Confettura di albicocche', 'cooked_grams', '{breakfast_cho}', 'breakfast:confettura', NULL, 'f', 'f', 'f', 200, 't'),
('jam_preserves', 169641, 'Confettura', 'cooked_grams', '{breakfast_cho}', 'breakfast:confettura', NULL, 'f', 'f', 'f', 150, 't'),
('jerusalem_artichoke', 169236, 'Topinambur', 'dry_grams', '{lunch_veg,dinner_veg}', NULL, NULL, 'f', 'f', 'f', 300, 't'),
('jujube', 168151, 'Giuggiole', 'dry_grams', '{snack_cho}', NULL, NULL, 'f', 'f', 'f', 300, 't'),
('kale_raw', 168421, 'Cavolo riccio', 'dry_grams', '{lunch_veg,dinner_veg}', NULL, NULL, 'f', 'f', 'f', 150, 't'),
('kamut_dry', 169743, 'Kamut (grano khorasan)', 'dry_grams', '{lunch_carb,dinner_carb}', 'carb:kamut', 'carb_starch', 'f', 'f', 'f', 200, 't'),
('kefir', 170904, 'Kefir', 'ml', '{breakfast_pro}', 'breakfast:kefir', NULL, 'f', 'f', 't', 100, 't'),
('kiwi_raw', 327046, 'Kiwi', 'dry_grams', '{snack_cho}', NULL, NULL, 'f', 'f', 'f', 100, 't'),
('kohlrabi', 168424, 'Cavolo rapa', 'dry_grams', '{lunch_veg,dinner_veg}', NULL, NULL, 'f', 'f', 'f', 300, 't'),
('kumquat', 168154, 'Kumquat', 'dry_grams', '{snack_cho}', 'cho:agrumi', NULL, 'f', 'f', 'f', 300, 't'),
('lamb_chops', 172493, 'Costolette d''agnello', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:agnello', NULL, 't', 'f', 'f', 200, 't'),
('lamb_ground', 172544, 'Macinato d''agnello', 'cooked_grams', '{lunch_pro,dinner_pro}', 'prot:agnello', NULL, 't', 'f', 'f', 200, 't'),
('lamb_leg', 172486, 'Agnello (coscia)', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:agnello', NULL, 't', 'f', 'f', 150, 't'),
('lamb_stew', 172508, 'Spezzatino d''agnello', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:agnello', NULL, 't', 'f', 'f', 300, 't'),
('leek', 169246, 'Porro', 'dry_grams', '{lunch_veg,dinner_veg}', NULL, NULL, 'f', 'f', 'f', 150, 't')
on conflict (canonical_key) do nothing;

insert into public.nutrition_menu_foods (canonical_key, fdc_id, label_it, serving_basis, pool_keys, rotation_key, carb_family, is_meat, is_fish, is_animal_product, sort_priority, is_active) values
('legumes_cooked', 172421, 'Legumi', 'cooked_grams', '{lunch_pro,dinner_pro}', 'prot:legumi', NULL, 'f', 'f', 'f', 100, 't'),
('lentils_green', 172420, 'Lenticchie verdi', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:lenticchie', NULL, 'f', 'f', 'f', 150, 't'),
('lentils_red', 174284, 'Lenticchie rosse', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:lenticchie', NULL, 'f', 'f', 'f', 200, 't'),
('lettuce_butterhead', 168429, 'Lattuga cappuccio', 'dry_grams', '{lunch_veg,dinner_veg}', 'veg:insalate', NULL, 'f', 'f', 'f', 200, 't'),
('lettuce_green_leaf', 169249, 'Lattuga foglia verde', 'dry_grams', '{lunch_veg,dinner_veg}', 'veg:lattuga', NULL, 'f', 'f', 'f', 200, 't'),
('lettuce_iceberg', 2346388, 'Lattuga iceberg', 'dry_grams', '{lunch_veg,dinner_veg}', 'veg:insalate', NULL, 'f', 'f', 'f', 200, 't'),
('lettuce_red_leaf', 168431, 'Lattuga rossa', 'dry_grams', '{lunch_veg,dinner_veg}', 'veg:lattuga', NULL, 'f', 'f', 'f', 200, 't'),
('lettuce_romaine', 169247, 'Lattuga romana', 'dry_grams', '{lunch_veg,dinner_veg}', NULL, NULL, 'f', 'f', 'f', 150, 't'),
('lima_beans', 174253, 'Fagioli di Spagna', 'cooked_grams', '{lunch_pro,dinner_pro}', NULL, NULL, 'f', 'f', 'f', 200, 't'),
('lobster', 174208, 'Astice', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:astice', NULL, 'f', 't', 'f', 300, 't'),
('loquat', 169908, 'Nespole', 'dry_grams', '{snack_cho}', NULL, NULL, 'f', 'f', 'f', 100, 't'),
('lupins', 172424, 'Lupini', 'cooked_grams', '{lunch_pro,dinner_pro}', 'prot:lupini', NULL, 'f', 'f', 'f', 100, 't'),
('lychee', 169086, 'Litchi', 'dry_grams', '{snack_cho}', NULL, NULL, 'f', 'f', 'f', 300, 't'),
('macadamia_nuts', 2515378, 'Noci macadamia', 'dry_grams', '{breakfast_fat}', NULL, NULL, 'f', 'f', 'f', 300, 't'),
('mackerel_atlantic', 175119, 'Sgombro', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:sgombro', NULL, 'f', 't', 'f', 150, 't'),
('mackerel_canned', 175121, 'Sgombro in scatola', 'cooked_grams', '{lunch_pro,dinner_pro}', NULL, NULL, 'f', 't', 'f', 200, 't'),
('mahimahi', 171959, 'Lampuga', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:lampuga', NULL, 'f', 't', 'f', 300, 't'),
('mango', 169910, 'Mango', 'dry_grams', '{snack_cho}', NULL, NULL, 'f', 'f', 'f', 300, 't'),
('marmalade_orange', 168819, 'Marmellata d''arance', 'cooked_grams', '{breakfast_cho}', 'breakfast:confettura', NULL, 'f', 'f', 'f', 200, 't'),
('melon_cantaloupe', 746770, 'Melone', 'dry_grams', '{snack_cho}', NULL, NULL, 'f', 'f', 'f', 100, 't'),
('melon_honeydew', 2710816, 'Melone bianco', 'dry_grams', '{snack_cho}', 'cho:melone', NULL, 'f', 'f', 'f', 150, 't'),
('milk_semi_skimmed', 746778, 'Latte parzialmente scremato', 'ml', '{breakfast_pro}', 'breakfast:latte', NULL, 'f', 'f', 't', 200, 't'),
('milk_skim', 746776, 'Latte scremato', 'ml', '{breakfast_pro}', 'breakfast:latte', NULL, 'f', 'f', 't', 150, 't'),
('milk_whole', 746782, 'Latte', 'ml', '{breakfast_pro}', 'breakfast:latte', NULL, 'f', 'f', 't', 100, 't'),
('millet', 168871, 'Miglio', 'cooked_grams', '{lunch_carb,dinner_carb}', 'carb:miglio', 'carb_starch', 'f', 'f', 'f', 150, 't'),
('mixed_fruit', 2346411, 'Frutta mista', 'dry_grams', '{snack_cho}', NULL, NULL, 'f', 'f', 'f', 100, 'f'),
('mixed_nuts', 170588, 'Frutta secca mista', 'dry_grams', '{breakfast_fat}', NULL, NULL, 'f', 'f', 'f', 300, 't'),
('mixed_veg', 168462, 'Insalata mista', 'dry_grams', '{lunch_veg,dinner_veg}', NULL, NULL, 'f', 'f', 'f', 100, 'f'),
('monkfish', 173676, 'Rana pescatrice', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:rana_pescatrice', NULL, 'f', 't', 'f', 200, 't'),
('mortadella', 174573, 'Mortadella', 'dry_grams', '{snack_pro}', NULL, NULL, 't', 'f', 'f', 200, 't'),
('mozzarella', 170847, 'Mozzarella', 'dry_grams', '{lunch_pro,dinner_pro,snack_pro}', 'prot:mozzarella', NULL, 'f', 'f', 't', 100, 't'),
('mozzarella_pizza', 170846, 'Mozzarella per pizza', 'dry_grams', '{lunch_pro,dinner_pro,snack_pro}', 'prot:mozzarella', NULL, 'f', 'f', 't', 200, 't'),
('mozzarella_whole', 170845, 'Fiordilatte', 'dry_grams', '{lunch_pro,dinner_pro,snack_pro}', 'prot:mozzarella', NULL, 'f', 'f', 't', 200, 't'),
('mulberries', 169913, 'Gelsi', 'dry_grams', '{snack_cho}', NULL, NULL, 'f', 'f', 'f', 300, 't'),
('mullet', 175123, 'Cefalo', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:cefalo', NULL, 'f', 't', 'f', 300, 't'),
('mung_sprouts', 169957, 'Germogli di soia', 'dry_grams', '{lunch_veg,dinner_veg}', 'veg:germogli', NULL, 'f', 'f', 'f', 300, 't'),
('mushrooms_chanterelle', 168422, 'Funghi finferli', 'dry_grams', '{lunch_veg,dinner_veg}', 'veg:funghi', NULL, 'f', 'f', 'f', 200, 't'),
('mushrooms_crimini', 168434, 'Funghi cremini', 'dry_grams', '{lunch_veg,dinner_veg}', 'veg:funghi', NULL, 'f', 'f', 'f', 150, 't'),
('mushrooms_oyster', 168580, 'Funghi pleurotus', 'dry_grams', '{lunch_veg,dinner_veg}', 'veg:funghi', NULL, 'f', 'f', 'f', 200, 't'),
('mushrooms_portobello', 169255, 'Funghi portobello', 'dry_grams', '{lunch_veg,dinner_veg}', 'veg:funghi', NULL, 'f', 'f', 'f', 200, 't'),
('mushrooms_shiitake', 169242, 'Funghi shiitake', 'dry_grams', '{lunch_veg,dinner_veg}', 'veg:funghi', NULL, 'f', 'f', 'f', 200, 't'),
('mushrooms_white', 169251, 'Funghi champignon', 'dry_grams', '{lunch_veg,dinner_veg}', NULL, NULL, 'f', 'f', 'f', 150, 't'),
('mussels', 174216, 'Cozze', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:cozze', NULL, 'f', 't', 'f', 100, 't'),
('nectarine', 169914, 'Nettarine', 'dry_grams', '{snack_cho}', 'cho:pesche', NULL, 'f', 'f', 'f', 200, 't'),
('oat_bran', 168872, 'Crusca d''avena', 'dry_grams', '{breakfast_cho}', 'breakfast:oat', NULL, 'f', 'f', 'f', 300, 't'),
('oat_dry', 172989, 'Fiocchi d''avena', 'dry_grams', '{breakfast_cho}', 'breakfast:oat', NULL, 'f', 'f', 'f', 100, 't'),
('ocean_perch', 175125, 'Sebaste', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:sebaste', NULL, 'f', 't', 'f', 300, 't'),
('octopus', 174218, 'Polpo', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:polpo', NULL, 'f', 't', 'f', 150, 't'),
('olive_oil', 171413, 'Olio EVO', 'ml', '{breakfast_fat}', NULL, NULL, 'f', 'f', 'f', 100, 't'),
('olives_black_table', 169094, 'Olive nere', 'cooked_grams', '{breakfast_fat}', 'olives_table', NULL, 'f', 'f', 'f', 150, 't'),
('olives_green_table', 169096, 'Olive verdi', 'cooked_grams', '{breakfast_fat}', 'olives_table', NULL, 'f', 'f', 'f', 150, 't'),
('onion', 170000, 'Cipolla', 'dry_grams', '{lunch_veg,dinner_veg}', NULL, NULL, 'f', 'f', 'f', 150, 't'),
('onion_red', 790577, 'Cipolla rossa', 'dry_grams', '{lunch_veg,dinner_veg}', 'veg:cipolla', NULL, 'f', 'f', 'f', 150, 't'),
('onion_white', 1104962, 'Cipolla bianca', 'dry_grams', '{lunch_veg,dinner_veg}', 'veg:cipolla', NULL, 'f', 'f', 'f', 200, 't'),
('orange_navel', 746771, 'Arancia navel', 'dry_grams', '{snack_cho}', 'cho:agrumi', NULL, 'f', 'f', 'f', 150, 't'),
('orange_raw', 169097, 'Arancia', 'dry_grams', '{snack_cho}', NULL, NULL, 'f', 'f', 'f', 100, 't'),
('orange_valencia', 169916, 'Arancia Valencia', 'dry_grams', '{snack_cho}', 'cho:agrumi', NULL, 'f', 'f', 'f', 200, 't'),
('oysters', 174219, 'Ostriche', 'dry_grams', '{lunch_pro,dinner_pro}', NULL, NULL, 'f', 't', 'f', 200, 't'),
('pancakes_plain', 175009, 'Pancake', 'dry_grams', '{breakfast_cho}', 'breakfast:pancake', NULL, 'f', 'f', 't', 100, 't'),
('papaya', 169926, 'Papaya', 'dry_grams', '{snack_cho}', NULL, NULL, 'f', 'f', 'f', 300, 't'),
('parmigiano_reggiano', 170848, 'Parmigiano Reggiano', 'dry_grams', '{lunch_pro,dinner_pro,snack_pro}', 'prot:formaggio_stagionato', NULL, 'f', 'f', 't', 150, 't'),
('parsnip', 2747659, 'Pastinaca', 'dry_grams', '{lunch_veg,dinner_veg}', NULL, NULL, 'f', 'f', 'f', 200, 't'),
('passion_fruit', 169108, 'Frutto della passione', 'dry_grams', '{snack_cho}', NULL, NULL, 'f', 'f', 'f', 300, 't'),
('pasta_corn_gf', 168899, 'Pasta di mais (senza glutine)', 'dry_grams', '{lunch_carb,dinner_carb}', 'carb:pasta_senza_glutine', 'carb_starch', 'f', 'f', 'f', 200, 't'),
('pasta_dry', 168927, 'Pasta di semola', 'dry_grams', '{lunch_carb,dinner_carb}', 'carb:pasta', 'carb_starch', 'f', 'f', 'f', 100, 't'),
('pasta_egg', 169731, 'Pasta all''uovo', 'dry_grams', '{lunch_carb,dinner_carb}', 'carb:pasta', 'carb_starch', 'f', 'f', 't', 150, 't'),
('pasta_spinach', 169733, 'Pasta agli spinaci', 'dry_grams', '{lunch_carb,dinner_carb}', 'carb:pasta', 'carb_starch', 'f', 'f', 't', 300, 't'),
('pasta_whole', 168915, 'Pasta integrale', 'dry_grams', '{lunch_carb,dinner_carb}', 'carb:pasta', 'carb_starch', 'f', 'f', 'f', 150, 't'),
('peach', 325430, 'Pesca', 'dry_grams', '{snack_cho}', NULL, NULL, 'f', 'f', 'f', 100, 't'),
('peaches_dried', 169934, 'Pesche secche', 'dry_grams', '{snack_cho}', 'cho:pesca', NULL, 'f', 'f', 'f', 200, 't'),
('peanut_butter', 2262072, 'Burro di arachidi', 'dry_grams', '{breakfast_fat}', NULL, NULL, 'f', 'f', 'f', 100, 't'),
('peanuts', 172430, 'Arachidi', 'dry_grams', '{breakfast_fat}', 'fat:arachidi', NULL, 'f', 'f', 'f', 200, 't'),
('pear_kaiser', 167778, 'Pera Kaiser', 'dry_grams', '{snack_cho}', 'cho:pera', NULL, 'f', 'f', 'f', 200, 't'),
('pear_raw', 169118, 'Pera', 'dry_grams', '{snack_cho}', NULL, NULL, 'f', 'f', 'f', 100, 't'),
('pear_williams', 746773, 'Pera Williams', 'dry_grams', '{snack_cho}', 'cho:pera', NULL, 'f', 'f', 'f', 150, 't'),
('pears_dried', 169121, 'Pere secche', 'dry_grams', '{snack_cho}', 'cho:pera', NULL, 'f', 'f', 'f', 200, 't'),
('peas_green', 170419, 'Piselli', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:piselli', NULL, 'f', 'f', 'f', 150, 't'),
('pecans', 170182, 'Noci pecan', 'dry_grams', '{breakfast_fat}', NULL, NULL, 'f', 'f', 'f', 300, 't'),
('pecorino_romano', 171249, 'Pecorino romano', 'dry_grams', '{snack_pro}', 'prot:formaggio_stagionato', NULL, 'f', 'f', 't', 200, 't'),
('perch', 173678, 'Pesce persico', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:persico', NULL, 'f', 't', 'f', 200, 't'),
('persimmon', 169941, 'Cachi', 'dry_grams', '{snack_cho}', NULL, NULL, 'f', 'f', 'f', 100, 't'),
('pheasant', 174473, 'Fagiano', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:fagiano', NULL, 't', 'f', 'f', 300, 't'),
('pike', 173680, 'Luccio', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:luccio', NULL, 'f', 't', 'f', 300, 't'),
('pine_nuts', 2346392, 'Pinoli', 'dry_grams', '{breakfast_fat}', NULL, NULL, 'f', 'f', 'f', 100, 't'),
('pineapple', 2346398, 'Ananas', 'dry_grams', '{snack_cho}', NULL, NULL, 'f', 'f', 'f', 100, 't'),
('pistachios', 2515379, 'Pistacchi', 'dry_grams', '{breakfast_fat}', NULL, NULL, 'f', 'f', 'f', 100, 't'),
('plum', 169949, 'Susine', 'dry_grams', '{snack_cho}', 'cho:prugne', NULL, 'f', 'f', 'f', 100, 't'),
('pollock', 173725, 'Merluzzo dell''Alaska', 'dry_grams', '{lunch_pro,dinner_pro}', NULL, NULL, 'f', 't', 'f', 150, 't'),
('pomegranate', 169134, 'Melograno', 'dry_grams', '{snack_cho}', NULL, NULL, 'f', 'f', 'f', 200, 't'),
('porgy', 175141, 'Pagello', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:pagello', NULL, 'f', 't', 'f', 200, 't'),
('pork_chop', 168240, 'Braciola di maiale', 'cooked_grams', '{lunch_pro,dinner_pro}', 'prot:maiale', NULL, 't', 'f', 'f', 150, 't'),
('pork_ground', 168374, 'Macinato di maiale', 'cooked_grams', '{lunch_pro,dinner_pro}', 'prot:maiale', NULL, 't', 'f', 'f', 150, 't'),
('pork_leg', 167816, 'Fesa di maiale', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:maiale', NULL, 't', 'f', 'f', 200, 't'),
('pork_loin', 2646168, 'Lonza di maiale', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:maiale', NULL, 't', 'f', 'f', 150, 't'),
('pork_shank', 168227, 'Stinco di maiale', 'cooked_grams', '{lunch_pro,dinner_pro}', 'prot:maiale', NULL, 't', 'f', 'f', 200, 't'),
('pork_tenderloin', 168249, 'Filetto di maiale', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:maiale', NULL, 't', 'f', 'f', 200, 't'),
('potato_cooked', 170093, 'Patate', 'cooked_grams', '{lunch_carb,dinner_carb}', 'carb:patate', 'carb_starch', 'f', 'f', 'f', 100, 't'),
('prickly_pear', 167750, 'Fichi d''India', 'dry_grams', '{snack_cho}', NULL, NULL, 'f', 'f', 'f', 200, 't'),
('prosciutto_crudo', 167876, 'Prosciutto crudo', 'dry_grams', '{lunch_pro,dinner_pro,snack_pro}', NULL, NULL, 't', 'f', 'f', 100, 't'),
('provolone', 170850, 'Provolone', 'dry_grams', '{lunch_pro,dinner_pro,snack_pro}', 'prot:formaggio_stagionato', NULL, 'f', 'f', 't', 200, 't')
on conflict (canonical_key) do nothing;

insert into public.nutrition_menu_foods (canonical_key, fdc_id, label_it, serving_basis, pool_keys, rotation_key, carb_family, is_meat, is_fish, is_animal_product, sort_priority, is_active) values
('prunes', 168162, 'Prugne secche', 'dry_grams', '{snack_cho}', 'cho:prugne', NULL, 'f', 'f', 'f', 200, 't'),
('puffed_rice', 173912, 'Riso soffiato', 'dry_grams', '{breakfast_cho}', 'breakfast:cereali', NULL, 'f', 'f', 'f', 200, 't'),
('puffed_wheat', 173913, 'Grano soffiato', 'dry_grams', '{breakfast_cho}', 'breakfast:cereali', NULL, 'f', 'f', 'f', 300, 't'),
('pumpkin_seeds_raw', 170556, 'Semi di zucca', 'dry_grams', '{breakfast_fat}', NULL, NULL, 'f', 'f', 'f', 100, 't'),
('purslane', 169274, 'Portulaca', 'dry_grams', '{lunch_veg,dinner_veg}', NULL, NULL, 'f', 'f', 'f', 300, 't'),
('quail', 172419, 'Quaglia', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:quaglia', NULL, 't', 'f', 'f', 300, 't'),
('quince', 168163, 'Mele cotogne', 'dry_grams', '{snack_cho}', NULL, NULL, 'f', 'f', 'f', 200, 't'),
('quinoa_dry', 168874, 'Quinoa', 'dry_grams', '{lunch_carb,dinner_carb}', 'carb:quinoa', 'carb_starch', 'f', 'f', 'f', 100, 't'),
('rabbit', 172521, 'Coniglio', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:coniglio', NULL, 't', 'f', 'f', 150, 't'),
('radicchio', 2747664, 'Radicchio', 'dry_grams', '{lunch_veg,dinner_veg}', 'veg:cicoria', NULL, 'f', 'f', 'f', 100, 't'),
('radish', 2747665, 'Ravanelli', 'dry_grams', '{lunch_veg,dinner_veg}', NULL, NULL, 'f', 'f', 'f', 200, 't'),
('raisins', 168166, 'Uvetta', 'dry_grams', '{snack_cho}', NULL, NULL, 'f', 'f', 'f', 100, 't'),
('raspberries', 2346410, 'Lamponi', 'dry_grams', '{snack_cho}', NULL, NULL, 'f', 'f', 'f', 100, 't'),
('rice_arborio', 168931, 'Riso Arborio', 'dry_grams', '{lunch_carb,dinner_carb}', 'carb:riso', 'carb_starch', 'f', 'f', 'f', 150, 't'),
('rice_black', 2710825, 'Riso venere', 'dry_grams', '{lunch_carb,dinner_carb}', 'carb:riso', 'carb_starch', 'f', 'f', 'f', 200, 't'),
('rice_brown', 169704, 'Riso integrale', 'cooked_grams', '{lunch_carb,dinner_carb}', 'carb:riso', 'carb_starch', 'f', 'f', 'f', 150, 't'),
('rice_cakes', 170250, 'Gallette di riso', 'dry_grams', '{breakfast_cho}', 'breakfast:gallette', NULL, 'f', 'f', 'f', 100, 't'),
('rice_cream', 173900, 'Crema di riso', 'dry_grams', '{breakfast_cho}', NULL, NULL, 'f', 'f', 'f', 300, 't'),
('rice_dry', 169756, 'Riso', 'dry_grams', '{lunch_carb,dinner_carb}', 'carb:riso', 'carb_starch', 'f', 'f', 'f', 100, 't'),
('rice_parboiled', 169758, 'Riso parboiled', 'dry_grams', '{lunch_carb,dinner_carb}', 'carb:riso', 'carb_starch', 'f', 'f', 'f', 200, 't'),
('rice_red', 2710838, 'Riso rosso', 'dry_grams', '{lunch_carb,dinner_carb}', 'carb:riso', 'carb_starch', 'f', 'f', 'f', 200, 't'),
('rice_wild', 169726, 'Riso selvaggio', 'dry_grams', '{lunch_carb,dinner_carb}', 'carb:riso', 'carb_starch', 'f', 'f', 'f', 300, 't'),
('ricotta_cheese', 170851, 'Ricotta', 'dry_grams', '{breakfast_pro}', NULL, NULL, 'f', 'f', 't', 100, 't'),
('roll_hard', 175031, 'Panino (rosetta)', 'dry_grams', '{breakfast_cho}', 'breakfast:bread', NULL, 'f', 'f', 'f', 150, 't'),
('roll_whole_wheat', 172794, 'Panino integrale', 'dry_grams', '{breakfast_cho}', 'breakfast:bread', NULL, 'f', 'f', 'f', 200, 't'),
('rusk_toast', 174981, 'Fette biscottate', 'dry_grams', '{breakfast_cho}', 'breakfast:fette', NULL, 'f', 'f', 't', 100, 't'),
('rutabaga', 168454, 'Navone', 'dry_grams', '{lunch_veg,dinner_veg}', NULL, NULL, 'f', 'f', 'f', 300, 't'),
('rye_grain', 168884, 'Segale', 'dry_grams', '{lunch_carb,dinner_carb}', 'carb:segale', 'carb_starch', 'f', 'f', 'f', 300, 't'),
('salame', 174603, 'Salame', 'dry_grams', '{snack_pro,lunch_pro,dinner_pro}', NULL, NULL, 't', 'f', 'f', 200, 't'),
('salmon_canned', 173724, 'Salmone in scatola', 'cooked_grams', '{lunch_pro,dinner_pro}', NULL, NULL, 'f', 't', 'f', 150, 't'),
('salsiccia', 171631, 'Salsiccia', 'dry_grams', '{lunch_pro,dinner_pro}', NULL, NULL, 't', 'f', 'f', 200, 't'),
('salt_cod', 174190, 'Baccalà', 'dry_grams', '{lunch_pro,dinner_pro}', NULL, NULL, 'f', 't', 'f', 150, 't'),
('sardines', 175139, 'Sardine', 'cooked_grams', '{lunch_pro,dinner_pro}', 'prot:sardine', NULL, 'f', 't', 'f', 150, 't'),
('scallops', 174220, 'Capesante', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:capesante', NULL, 'f', 't', 'f', 200, 't'),
('sea_bass', 175142, 'Branzino', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:branzino', NULL, 'f', 't', 'f', 100, 't'),
('semolina', 169715, 'Semolino', 'dry_grams', '{breakfast_cho}', 'breakfast:semolino', NULL, 'f', 'f', 'f', 200, 't'),
('sesame_seeds', 170150, 'Semi di sesamo', 'dry_grams', '{breakfast_fat}', 'fat:sesamo', NULL, 'f', 'f', 'f', 200, 't'),
('shallots', 170499, 'Scalogno', 'dry_grams', '{lunch_veg,dinner_veg}', NULL, NULL, 'f', 'f', 'f', 200, 't'),
('shrimp', 175180, 'Gamberi', 'cooked_grams', '{lunch_pro,dinner_pro}', 'prot:gamberi', NULL, 'f', 't', 'f', 150, 't'),
('smoked_salmon', 173687, 'Salmone affumicato', 'cooked_grams', '{lunch_pro,dinner_pro}', 'salmon', NULL, 'f', 't', 'f', 150, 't'),
('snow_peas', 170010, 'Taccole', 'dry_grams', '{lunch_veg,dinner_veg}', NULL, NULL, 'f', 'f', 'f', 200, 't'),
('sole', 174196, 'Sogliola', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:sogliola', NULL, 'f', 't', 'f', 100, 't'),
('sorghum', 169716, 'Sorgo', 'dry_grams', '{lunch_carb,dinner_carb}', 'carb:sorgo', 'carb_starch', 'f', 'f', 'f', 300, 't'),
('sour_cherries', 173954, 'Amarene', 'dry_grams', '{snack_cho}', 'cho:ciliegie', NULL, 'f', 'f', 'f', 200, 't'),
('sour_cream', 2346387, 'Panna acida', 'ml', '{breakfast_fat}', NULL, NULL, 'f', 'f', 't', 200, 't'),
('soybeans_cooked', 174271, 'Soia', 'cooked_grams', '{lunch_pro,dinner_pro}', 'prot:soia', NULL, 'f', 'f', 'f', 200, 't'),
('soybeans_roasted', 172441, 'Soia tostata', 'dry_grams', '{snack_pro}', NULL, NULL, 'f', 'f', 'f', 300, 't'),
('soymilk', 172446, 'Latte di soia', 'ml', '{breakfast_pro}', 'breakfast:latte', NULL, 'f', 'f', 'f', 100, 't'),
('spaghetti_squash', 169298, 'Zucca spaghetti', 'dry_grams', '{lunch_veg,dinner_veg}', NULL, NULL, 'f', 'f', 'f', 300, 't'),
('spinach_raw', 168462, 'Spinaci', 'dry_grams', '{lunch_veg,dinner_veg}', NULL, NULL, 'f', 'f', 'f', 100, 't'),
('spiny_lobster', 174211, 'Aragosta', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:aragosta', NULL, 'f', 't', 'f', 200, 't'),
('split_peas', 172429, 'Piselli spezzati', 'cooked_grams', '{lunch_pro,dinner_pro}', 'prot:piselli', NULL, 'f', 'f', 'f', 300, 't'),
('spring_onion', 170005, 'Cipollotto', 'dry_grams', '{lunch_veg,dinner_veg}', 'veg:cipolla', NULL, 'f', 'f', 'f', 150, 't'),
('squid', 174223, 'Calamari', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:calamari', NULL, 'f', 't', 'f', 150, 't'),
('strawberries_raw', 167762, 'Fragole', 'dry_grams', '{snack_cho}', NULL, NULL, 'f', 'f', 'f', 100, 't'),
('sturgeon', 173701, 'Storione', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:storione', NULL, 'f', 't', 'f', 300, 't'),
('sunflower_seeds', 2515381, 'Semi di girasole', 'dry_grams', '{breakfast_fat}', NULL, NULL, 'f', 'f', 'f', 200, 't'),
('sweet_corn', 169998, 'Mais dolce', 'dry_grams', '{lunch_veg,dinner_veg}', NULL, NULL, 'f', 'f', 'f', 200, 't'),
('sweet_potato', 168482, 'Patata dolce', 'dry_grams', '{lunch_carb,dinner_carb}', 'carb:patate', 'carb_starch', 'f', 'f', 'f', 150, 't'),
('swiss_chard', 169991, 'Bietole', 'dry_grams', '{lunch_veg,dinner_veg}', NULL, NULL, 'f', 'f', 'f', 150, 't'),
('swordfish', 173703, 'Pesce spada', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:pesce_spada', NULL, 'f', 't', 'f', 100, 't'),
('tahini', 170189, 'Tahini', 'dry_grams', '{breakfast_fat}', 'fat:sesamo', NULL, 'f', 'f', 'f', 300, 't'),
('tangerine', 169105, 'Mandarino', 'dry_grams', '{snack_cho}', NULL, NULL, 'f', 'f', 'f', 100, 't'),
('teff', 169747, 'Teff', 'dry_grams', '{lunch_carb,dinner_carb}', 'carb:teff', 'carb_starch', 'f', 'f', 'f', 300, 't'),
('tempeh', 174272, 'Tempeh', 'dry_grams', '{dinner_pro}', NULL, NULL, 'f', 'f', 'f', 100, 't'),
('tilapia', 175176, 'Tilapia', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:tilapia', NULL, 'f', 't', 'f', 300, 't'),
('tofu_firm', 172475, 'Tofu', 'dry_grams', '{lunch_pro,dinner_pro}', NULL, NULL, 'f', 'f', 'f', 100, 't'),
('tomato_raw', 170457, 'Pomodori', 'dry_grams', '{lunch_veg}', NULL, NULL, 'f', 'f', 'f', 100, 't'),
('tortilla_flour', 167535, 'Tortilla di frumento (wrap)', 'dry_grams', '{breakfast_cho}', 'breakfast:bread', NULL, 'f', 'f', 'f', 200, 't'),
('trout', 173717, 'Trota', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:trota', NULL, 'f', 't', 'f', 100, 't'),
('tuna_canned', 173708, 'Tonno in scatola', 'cooked_grams', '{lunch_pro,dinner_pro}', 'prot:tonno', NULL, 'f', 't', 'f', 150, 't'),
('tuna_canned_water', 171986, 'Tonno al naturale', 'cooked_grams', '{lunch_pro,dinner_pro}', 'prot:tonno', NULL, 'f', 't', 'f', 150, 't'),
('tuna_fresh', 173706, 'Tonno fresco', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:tonno', NULL, 'f', 't', 'f', 100, 't'),
('tuna_white_water', 171988, 'Tonno bianco al naturale', 'cooked_grams', '{lunch_pro,dinner_pro}', 'prot:tonno', NULL, 'f', 't', 'f', 200, 't'),
('turbot', 173710, 'Rombo', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:rombo', NULL, 'f', 't', 'f', 200, 't'),
('turkey_breast', 171098, 'Petto di tacchino', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:tacchino', NULL, 't', 'f', 'f', 150, 't'),
('turkey_breast_deli', 174572, 'Fesa di tacchino', 'dry_grams', '{snack_pro}', NULL, NULL, 't', 'f', 'f', 200, 't'),
('turkey_drumstick', 171136, 'Fuso di tacchino', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:tacchino_altri', NULL, 't', 'f', 'f', 300, 't'),
('turkey_ground', 172850, 'Macinato di tacchino', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:tacchino_altri', NULL, 't', 'f', 'f', 200, 't'),
('turkey_thigh', 171531, 'Coscia di tacchino', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:tacchino_altri', NULL, 't', 'f', 'f', 200, 't'),
('turnip', 2747674, 'Rape', 'dry_grams', '{lunch_veg,dinner_veg}', NULL, NULL, 'f', 'f', 'f', 200, 't'),
('veal_cutlet', 172643, 'Fesa di vitello', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:vitello', NULL, 't', 'f', 'f', 150, 't'),
('veal_ground', 175291, 'Macinato di vitello', 'cooked_grams', '{lunch_pro,dinner_pro}', 'prot:vitello', NULL, 't', 'f', 'f', 150, 't'),
('veal_loin', 173826, 'Vitello magro', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:vitello', NULL, 't', 'f', 'f', 150, 't'),
('veal_rib_chop', 173827, 'Costoletta di vitello', 'cooked_grams', '{lunch_pro,dinner_pro}', 'prot:vitello', NULL, 't', 'f', 'f', 150, 't'),
('veal_shoulder', 175282, 'Spezzatino di vitello', 'dry_grams', '{lunch_pro,dinner_pro}', 'prot:vitello', NULL, 't', 'f', 'f', 200, 't'),
('walnuts', 170187, 'Noci', 'dry_grams', '{breakfast_fat}', NULL, NULL, 'f', 'f', 'f', 100, 't'),
('watercress', 170068, 'Crescione', 'dry_grams', '{lunch_veg,dinner_veg}', NULL, NULL, 'f', 'f', 'f', 300, 't'),
('watermelon', 167765, 'Anguria', 'dry_grams', '{snack_cho}', NULL, NULL, 'f', 'f', 'f', 100, 't'),
('wheat_bran', 169722, 'Crusca di grano', 'dry_grams', '{breakfast_cho}', NULL, NULL, 'f', 'f', 'f', 250, 't'),
('wheat_durum', 169721, 'Grano duro (in chicchi)', 'dry_grams', '{lunch_carb,dinner_carb}', 'carb:grano', 'carb_starch', 'f', 'f', 'f', 200, 't'),
('wheat_germ', 168892, 'Germe di grano', 'dry_grams', '{breakfast_cho}', NULL, NULL, 'f', 'f', 'f', 300, 't'),
('whitefish', 173711, 'Coregone', 'dry_grams', '{lunch_pro,dinner_pro}', NULL, NULL, 'f', 't', 'f', 200, 't'),
('whiting', 173713, 'Merlano', 'dry_grams', '{lunch_pro,dinner_pro}', NULL, NULL, 'f', 't', 'f', 200, 't'),
('wild_boar', 175298, 'Cinghiale', 'cooked_grams', '{lunch_pro,dinner_pro}', 'prot:cinghiale', NULL, 't', 'f', 'f', 200, 't'),
('yogurt_greek', 170903, 'Yogurt greco', 'dry_grams', '{breakfast_pro,snack_pro}', 'breakfast:yogurt', NULL, 'f', 'f', 't', 100, 't'),
('yogurt_greek_nonfat', 330137, 'Yogurt greco 0%', 'dry_grams', '{breakfast_pro,snack_pro}', 'breakfast:yogurt', NULL, 'f', 'f', 't', 200, 't'),
('yogurt_greek_whole', 2259794, 'Yogurt greco intero', 'dry_grams', '{breakfast_pro,snack_pro}', 'breakfast:yogurt', NULL, 'f', 'f', 't', 300, 't'),
('yogurt_lowfat', 170886, 'Yogurt magro', 'dry_grams', '{breakfast_pro,snack_pro}', 'breakfast:yogurt', NULL, 'f', 'f', 't', 200, 't'),
('yogurt_plain', 171284, 'Yogurt bianco', 'dry_grams', '{breakfast_pro,snack_pro}', 'breakfast:yogurt', NULL, 'f', 'f', 't', 100, 't')
on conflict (canonical_key) do nothing;

insert into public.nutrition_menu_foods (canonical_key, fdc_id, label_it, serving_basis, pool_keys, rotation_key, carb_family, is_meat, is_fish, is_animal_product, sort_priority, is_active) values
('zucchini_raw', 169291, 'Zucchine', 'dry_grams', '{lunch_veg,dinner_veg}', NULL, NULL, 'f', 'f', 'f', 100, 't'),
('zucchini_yellow', 2685569, 'Zucchine gialle', 'dry_grams', '{lunch_veg,dinner_veg}', 'veg:zucchine', NULL, 'f', 'f', 'f', 300, 't')
on conflict (canonical_key) do nothing;
