-- ESERCIZI IN ITALIANO — nome, esecuzione ed errore tipico per i 50 esercizi che gli
-- atleti ricevono DAVVERO (55 righe di catalogo: quattro esercizi esistono in doppia
-- copia perché il catalogo è nato dalla fusione di tre librerie, e ricevono lo stesso
-- testo).
--
-- Perimetro scelto sui dati, non a occhio: sono le voci estratte dai piani veri in
-- produzione — 1.163 usi dal Builder del coach + 89 dal motore. Le prime otto coprono il
-- 95% degli allenamenti. Gli altri 182 esercizi del catalogo restano senza traduzione:
-- la UI mostra il nome inglese, esattamente come oggi.
--
-- REGOLE SEGUITE NEI TESTI:
--  * il nome è quello che un istruttore italiano userebbe davvero — «panca piana», non
--    «pressa da panca»; e resta l'inglese dove è il termine corrente anche da noi
--    (burpee, thruster, leg press, dip). Tradurre a forza è peggio che non tradurre.
--  * le istruzioni dicono posizione di partenza, movimento e dove arriva lo sforzo. MAI
--    serie, ripetizioni, carichi o percentuali: quelli sono competenza del coach.
--  * le voci di sport tecnico (judo, kata, muay thai, basket) descrivono cosa comporta la
--    seduta, non pretendono di insegnare la tecnica in due righe.
--
-- ⚠️ `name` NON viene toccato: è la chiave con cui i piani salvati ritrovano l'esercizio
-- (nei notes c'è solo «"label":"Back Squat"», nessun id). L'aggancio qui è per ID.
--
-- Rieseguibile: è un update per id, la seconda esecuzione riscrive gli stessi valori.
-- Applicare dall'editor SQL — MAI `supabase db push`.

update public.exercise e
set name_it = v.name_it,
    how_to_it = v.how_to_it,
    common_mistake_it = v.common_mistake_it
from (values
  ('empathy-b1x-arnoldpress', 'Arnold press con manubri', 'Seduto o in piedi, manubri davanti alle spalle con i palmi rivolti verso di te. Spingi verso l''alto ruotando i palmi in avanti mentre le braccia si distendono, poi torna giù ripercorrendo la stessa rotazione al contrario fino ai palmi verso il viso. Busto fermo, costole basse.', 'Inarcare la schiena per finire la spinta: il carico scende sulla zona lombare invece che sulle spalle.'),
  ('empathy-b1x-assisteddip', 'Dip assistiti alla macchina', 'Regola il carico di assistenza, appoggia le ginocchia sul cuscino e impugna le maniglie a braccia distese. Scendi piegando i gomiti finché le spalle arrivano all''altezza dei gomiti, cioè braccio circa parallelo a terra, busto appena inclinato avanti, poi risali spingendo.', 'Aprire i gomiti verso l''esterno invece di tenerli vicini al busto: la spalla si carica e la spinta perde linea.'),
  ('empathy-b1x-assistedpullup', 'Trazioni assistite alla macchina', 'Imposta il carico di assistenza, appoggia ginocchia o piedi sul cuscino e impugna la barra a presa prona più larga delle spalle. Tira portando i gomiti verso il basso finché il mento supera la barra, poi scendi lentamente fino a braccia distese. Spalle lontane dalle orecchie.', 'Mettere troppa assistenza e spingere sul cuscino con le gambe: la trazione la fa la macchina, non il dorso.'),
  ('empathy-b1-backsquat', 'Back squat (bilanciere dietro)', 'Regola i fermi di sicurezza prima di sfilare il bilanciere dal rack sui trapezi, poi fai due passi indietro; piedi a larghezza spalle e punte in fuori. Scendi piegando anche e ginocchia insieme fino alla massima profondità in cui la schiena resta compatta e i talloni a terra, poi risali spingendo con tutto il piede.', 'Ginocchia che collassano verso l''interno nella risalita: tienile in linea con le punte dei piedi.'),
  ('gym_back_squat', 'Back squat (bilanciere dietro)', 'Regola i fermi di sicurezza prima di sfilare il bilanciere dal rack sui trapezi, poi fai due passi indietro; piedi a larghezza spalle e punte in fuori. Scendi piegando anche e ginocchia insieme fino alla massima profondità in cui la schiena resta compatta e i talloni a terra, poi risali spingendo con tutto il piede.', 'Ginocchia che collassano verso l''interno nella risalita: tienile in linea con le punte dei piedi.'),
  ('empathy-b1x-sleddragbackward', 'Trascinamento della slitta all''indietro', 'Corda o cinghie in mano, dai le spalle alla direzione di marcia e cammina all''indietro tirando la slitta. Busto leggermente inclinato indietro, braccia in tensione, passi corti e appoggio pieno del piede. Il carico si sente sulla parte anteriore delle cosce e attorno al ginocchio.', 'Fare passi lunghi cercando velocità: si perde tensione e il ginocchio arriva a fine corsa di colpo.'),
  ('empathy-b1x-bandpullapart', 'Pull-apart con elastico (dorso alto)', 'In piedi, elastico teso fra le mani davanti al petto con le braccia distese all''altezza delle spalle. Apri le braccia portando le mani verso l''esterno e avvicinando le scapole, poi lascia tornare l''elastico senza mollarlo di colpo. Le braccia restano distese e il collo rilassato.', 'Piegare i gomiti o inarcare la schiena per aprire di più: il dorso alto smette di lavorare.'),
  ('gym_band_squat', 'Squat con elastico', 'Elastico ancorato al rack e passato sulle spalle o attorno ai fianchi, piedi a larghezza spalle. Scendi in squat controllando la trazione dell''elastico, poi risali spingendo con tutto il piede: la resistenza cresce mano a mano che ti alzi, quindi accelera nella parte alta.', 'Lasciarsi tirare giù dall''elastico nella discesa invece di controllarla: si perde posizione sul fondo.'),
  ('empathy-b1x-shrug', 'Scrollate con bilanciere', 'In piedi col bilanciere davanti alle cosce, braccia distese e presa poco più larga delle anche. Solleva le spalle dritte verso le orecchie senza piegare i gomiti, fermati un istante in alto e lascia scendere le spalle senza lasciar cadere le spalle fino ad allungare di nuovo il trapezio.', 'Ruotare le spalle avanti e indietro invece di alzarle in verticale: la spalla lavora fuori dal suo asse.'),
  ('basket_transition_drill', 'Drill di transizione (basket)', 'Esercitazione a campo aperto con palla e coni: si ripetono transizioni fra difesa e attacco con cambi di direzione e ripartenze ad alta velocità e recuperi brevi. Allena l''accelerazione ripetuta e il controllo palla sotto affanno; la lettura tecnica la guida l''allenatore.', 'Rallentare i cambi di direzione per fare più ripetizioni: la qualità dell''appoggio è il senso dell''esercizio.'),
  ('empathy-b1x-battleropes', 'Battle ropes (funi ondulatorie)', 'Una corda per mano, piedi a larghezza spalle, ginocchia morbide e bacino leggermente indietro. Genera onde continue alternando le braccia, col busto fermo e le costole basse. Cede per prima la postura: quando ti stanchi il busto si raddrizza e le onde si appiattiscono.', 'Muovere solo gli avambracci: le onde si spengono a metà corda e lo sforzo resta tutto sulle spalle.'),
  ('empathy-b1x-bearcrawl', 'Bear crawl (camminata dell''orso)', 'In quadrupedia con le mani sotto le spalle e le ginocchia sotto le anche, sollevate di pochi centimetri da terra e schiena piatta. Avanza muovendo mano e piede opposti con passi corti, tenendo il bacino basso e fermo. Se inizia a ondeggiare, rallenta il passo.', 'Alzare il bacino o farlo oscillare di lato a ogni passo: il tronco smette di tenere la posizione.'),
  ('empathy-b1x-benchdip', 'Dip fra le panche (bench dip)', 'Mani sul bordo della panca alle tue spalle, dita in avanti, gambe distese davanti con i talloni a terra. Scendi piegando i gomiti indietro finché il braccio è circa parallelo a terra, poi risali distendendo le braccia. Il bacino resta vicino alla panca per tutta la salita.', 'Allontanare il bacino dalla panca: la spalla va in avanti e si carica la parte anteriore dell''articolazione.'),
  ('empathy-b1-bench', 'Panca piana con bilanciere', 'Prima di iniziare regola i fermi di sicurezza all''altezza del petto o fatti assistere. Sdraiato sulla panca, piedi a terra e scapole strette, impugna il bilanciere poco più largo delle spalle: portalo giù controllato fino a sfiorare lo sterno, poi spingilo in alto fino a braccia distese.', 'Far rimbalzare il bilanciere sul petto invece di fermarlo un istante e ripartire in controllo.'),
  ('empathy-b1-burpee', 'Burpee', 'Dalla posizione in piedi scendi con le mani a terra, porta i piedi indietro fino al plank e appoggia il petto; spingi sulle mani per tornare al plank, poi richiama i piedi sotto il bacino e risali, chiudendo con un saltello. Corpo compatto ogni volta che vai a terra.', 'Lasciar cadere il bacino quando arrivi a terra: la zona lombare si inarca a ogni ripetizione.'),
  ('empathy-b1x-cablecurl', 'Curl ai cavi', 'In piedi davanti alla puleggia bassa, impugna la barra o la maniglia a braccia distese con i gomiti vicini ai fianchi. Fletti i gomiti portando le mani verso le spalle senza spostarli in avanti, poi lascia scendere il cavo frenando la discesa fino a distendere del tutto le braccia.', 'Portare i gomiti in avanti o dondolare col busto per alzare di più: la tensione lascia il bicipite.'),
  ('empathy-b1-cablefly', 'Croci ai cavi', 'In piedi fra due pulegge, una maniglia per mano, un piede leggermente avanti e busto appena inclinato. Con i gomiti quasi fissi e solo un po'' piegati, porta le mani avanti e l''una verso l''altra davanti al petto, poi riapri le braccia senza far scattare i cavi fino a sentire tirare sul petto.', 'Piegare i gomiti durante la chiusura: diventa una spinta e il petto smette di lavorare in allungamento.'),
  ('empathy-b1x-cablepullthrough', 'Pull-through ai cavi', 'Corda al gancio basso del cavo: dai le spalle alla macchina, passa la corda fra le gambe e fai due passi avanti. Ginocchia morbide, manda indietro il bacino lasciando che la corda ti tiri, poi risali chiudendo le anche e stringendo i glutei. Lo sforzo si sente dietro le cosce.', 'Tirare la corda con le braccia invece di far chiudere le anche: lavorano le spalle e i glutei restano fuori.'),
  ('empathy-b1-chestsupportedrow', 'Rematore con appoggio al petto', 'Petto appoggiato allo schienale inclinato, piedi stabili, braccia distese verso il basso con manubri o maniglie. Tira portando i gomiti indietro e le scapole l''una verso l''altra, fermati quando le mani arrivano al fianco, poi accompagna il ritorno senza mollare la presa. Il petto resta appoggiato.', 'Staccare il petto dallo schienale per aiutarsi col busto: il lavoro passa dal dorso alla schiena bassa.'),
  ('empathy-b1x-chinup', 'Trazioni a presa supina', 'Appeso alla sbarra con presa supina a larghezza spalle, braccia distese e gambe ferme. Tira portando i gomiti in basso e il petto verso la sbarra fino a superarla col mento, poi scendi frenando la discesa fino a braccia di nuovo distese. Evita di dondolare con le gambe.', 'Fermare la discesa a metà senza mai distendere le braccia: il range si accorcia ripetizione dopo ripetizione.'),
  ('empathy-b1x-concentrationcurl', 'Curl in concentrazione', 'Seduto sulla panca a gambe divaricate, appoggia il gomito del braccio che lavora all''interno della coscia, manubrio a braccio disteso. Fletti il gomito portando il manubrio verso la spalla, poi scendi lentamente fino a distendere del tutto il braccio. Busto fermo.', 'Sollevare il gomito dalla coscia per finire la ripetizione: entra la spalla e il bicipite si scarica.'),
  ('empathy-b1x-crabwalk', 'Crab walk (camminata del granchio)', 'Seduto a terra, mani dietro il bacino con le dita verso i piedi, piedi appoggiati e ginocchia piegate; solleva il bacino fino a portare il busto quasi parallelo a terra. Cammina avanti e indietro alternando mano e piede opposti. Il primo a cedere è il bacino, che scende.', 'Lasciar scendere il bacino verso terra a ogni passo: spalle e glutei smettono di reggere la posizione.'),
  ('endurance_cycling_spin_ups', 'Spin-up in bici (agilità di pedalata)', 'Su rulli o strada piana con un rapporto leggero, alza la cadenza in modo progressivo fino al massimo che riesci a tenere senza rimbalzare sulla sella, poi torna alla pedalata normale. Lo sforzo è di gambe veloci e fluide, non di spinta sui pedali.', 'Salire di cadenza rimbalzando sulla sella: la pedalata perde fluidità e il senso del drill svanisce.'),
  ('empathy-b1-deadlift', 'Stacco da terra', 'Bilanciere sopra il mezzo piede, piedi a larghezza anche, presa poco fuori dalle ginocchia. Porta il petto alto e le spalle sopra il bilanciere, poi stacca spingendo il pavimento e distendendo anche e ginocchia insieme. Il bilanciere sale rasente le gambe fino a busto eretto.', 'Alzare il bacino prima del bilanciere: la schiena si arrotonda e il peso si allontana dalle gambe.'),
  ('empathy-b1x-deficitdeadlift', 'Stacco da terra in deficit', 'Stessa impostazione dello stacco, ma in piedi su un rialzo basso di due o cinque centimetri col bilanciere a terra. Il range più ampio porta le anche più in basso prima dello stacco; si sale distendendo anche e ginocchia insieme, bilanciere rasente le gambe.', 'Usare un rialzo troppo alto: la schiena si arrotonda già nella posizione di partenza, prima dello stacco.'),
  ('empathy-b1x-donkeycalfraise', 'Calf raise alla donkey machine', 'Alla macchina, fletti il busto in avanti fino a circa 90° appoggiandoti al supporto con mani o avambracci e sistema il cuscinetto sul bacino, non sulla schiena. Punte dei piedi sulla pedana e talloni liberi: lascia scendere i talloni finché senti tirare il polpaccio, poi sali sulle punte.', 'Molleggiare in basso e risalire di slancio: il polpaccio salta la parte utile e il tendine prende il colpo.'),
  ('gym_dumbbell_bench', 'Panca piana con manubri', 'Sdraiato sulla panca con i piedi a terra e le scapole strette, manubri all''altezza del petto e gomiti sotto i polsi. Spingi i manubri verso l''alto fino a braccia quasi distese, senza farli sbattere, poi riscendi controllando finché le mani sono a livello del petto.', 'Aprire i gomiti a novanta gradi rispetto al busto: la spalla si carica e la spinta perde stabilità.'),
  ('empathy-b1x-dumbbellbenchpress', 'Panca piana con manubri', 'Sdraiato sulla panca con i piedi a terra e le scapole strette, manubri all''altezza del petto e gomiti sotto i polsi. Spingi i manubri verso l''alto fino a braccia quasi distese, senza farli sbattere, poi riscendi controllando finché le mani sono a livello del petto.', 'Aprire i gomiti a novanta gradi rispetto al busto: la spalla si carica e la spinta perde stabilità.'),
  ('empathy-b1x-frogpump', 'Frog pump (ponte a rana)', 'Sdraiato a pancia in su con le spalle a terra, unisci le piante dei piedi e apri le ginocchia verso l''esterno, talloni vicini al bacino. Solleva il bacino spingendo con i talloni e stringendo i glutei in alto, poi torna giù senza appoggiare del tutto a terra.', 'Salire inarcando la zona lombare invece di chiudere l''anca stringendo i glutei in cima al movimento.'),
  ('empathy-b1-frontsquat', 'Front squat (bilanciere davanti)', 'Bilanciere in appoggio sui deltoidi anteriori, gomiti alti e dita sotto la barra, piedi a larghezza spalle. Scendi piegando anche e ginocchia tenendo il busto il più verticale possibile e i gomiti in alto, poi risali spingendo con tutto il piede.', 'Lasciar cadere i gomiti verso il basso: il bilanciere scivola avanti e il busto si chiude sotto il carico.'),
  ('boxing_bag_rounds', 'Intervalli al sacco', 'Lavoro a round sul sacco pesante con i guantoni. Guardia alta, piedi che si spostano, colpi che partono dalla rotazione di anche e busto e non solo dal braccio. Si alternano round di lavoro e pause brevi: conta la densità dei colpi, non la potenza del singolo.', 'Restare piantato davanti al sacco spingendo di braccia: senza rotazione i colpi caricano solo le spalle.'),
  ('judo_kuzushi_drill', 'Judo: kuzushi ed entrate di presa', 'Seduta tecnica sul tatami a coppie: si ripetono squilibri ed entrate di presa, alternando ripetizioni lente a serie più dinamiche col compagno che oppone resistenza. Allena tempi e presa più della forza; l''esecuzione tecnica va seguita e corretta dall''allenatore in sala.', 'Trasformare le entrate in strappi di forza sulla presa invece di cercare lo squilibrio del compagno.'),
  ('karate_kata_precision', 'Kata di precisione (karate)', 'Sessione di ripetizioni di kata a corpo libero, curando posizioni, traiettorie e tempi più della velocità. Si alternano passaggi eseguiti lenti per la precisione a esecuzioni a ritmo pieno. Impegno alto di concentrazione; la correzione tecnica spetta al maestro in sala.', 'Alzare la velocità prima che le posizioni siano stabili: la precisione cala e la sessione perde il suo scopo.'),
  ('empathy-b1-kbswing', 'Swing con kettlebell', 'Kettlebell a terra poco davanti a te, piedi a larghezza spalle. Manda indietro il bacino, aggancia il kettlebell fra le gambe e proiettalo avanti chiudendo di colpo le anche; il peso sale per slancio fino all''altezza del petto e ricade nel corridoio fra le gambe.', 'Sollevare il kettlebell con le spalle come in un''alzata frontale invece di lanciarlo con la spinta delle anche.'),
  ('empathy-b1-latpulldown', 'Lat machine avanti (pulldown)', 'Seduto alla lat machine con le cosce bloccate sotto i cuscinetti, impugna la barra più larga delle spalle a braccia distese. Tira la barra verso la parte alta del petto portando i gomiti in basso e indietro, poi lascia risalire frenando la risalita fino a distendere le braccia.', 'Sbilanciarsi indietro col busto e tirare a strappo: la barra scende ma il dorso non completa il movimento.'),
  ('empathy-b1-legextension', 'Leg extension (estensioni per i quadricipiti)', 'Seduto alla macchina con la schiena appoggiata, regola il rullo appena sopra i piedi e l''asse di rotazione all''altezza del ginocchio. Distendi le gambe fino a portare le ginocchia quasi dritte, fermati un istante in alto e torna giù frenando il ritorno senza far sbattere i pesi.', 'Lasciar ricadere il peso di colpo nella discesa: il ginocchio prende lo strappo a fine corsa.'),
  ('empathy-b1-legpress', 'Leg press', 'Siediti nella pressa con schiena e bacino aderenti allo schienale, piedi sulla pedana a larghezza anche. Sblocca i fermi e scendi piegando le ginocchia fino al punto più basso che riesci a controllare tenendo il bacino aderente, poi spingi con tutto il piede senza bloccare del tutto le ginocchia.', 'Spingere di punta lasciando staccare i talloni, o scendere tanto da far staccare il bacino dallo schienale.'),
  ('gym_leg_press', 'Leg press', 'Siediti nella pressa con schiena e bacino aderenti allo schienale, piedi sulla pedana a larghezza anche. Sblocca i fermi e scendi piegando le ginocchia fino al punto più basso che riesci a controllare tenendo il bacino aderente, poi spingi con tutto il piede senza bloccare del tutto le ginocchia.', 'Spingere di punta lasciando staccare i talloni, o scendere tanto da far staccare il bacino dallo schienale.'),
  ('empathy-b1-machinechestpress', 'Chest press alla macchina', 'Regola il sedile in modo che le maniglie siano all''altezza della parte bassa del petto; schiena appoggiata allo schienale e piedi a terra. Spingi le maniglie in avanti fino a braccia quasi distese, poi lascia rientrare frenando il rientro finché le mani tornano a fianco del petto.', 'Sedile troppo basso o troppo alto: si spinge in diagonale verso le spalle invece che all''altezza del petto.'),
  ('empathy-b1x-machinepullover', 'Pullover alla macchina', 'Seduto alla macchina con la schiena appoggiata e la cintura allacciata, aggancia gomiti o maniglie con le braccia alte sopra la testa. Porta le braccia in basso e in avanti fino all''altezza del busto ruotando attorno alla spalla, poi lascia risalire controllando.', 'Piegare i gomiti e tirare come in un pulldown: il dorso lavora poco e il carico passa alle braccia.'),
  ('muay_thai_pad_rounds', 'Round ai colpitori (Muay Thai)', 'Round ai colpitori con chi tiene i pad che detta le combinazioni: pugni, calci e ginocchia concatenati a ritmo alto, con pause brevi fra un round e l''altro. Allena resistenza specifica e coordinazione sotto affanno; la correzione dei colpi resta compito dell''allenatore.', 'Colpire più forte quando la stanchezza sale: la guardia si abbassa e la combinazione perde ritmo.'),
  ('empathy-b1-ohpress', 'Lento avanti con bilanciere', 'In piedi, bilanciere all''altezza delle clavicole con presa poco più larga delle spalle, gomiti sotto la barra e piedi a larghezza anche. Spingi in alto portando la testa appena indietro per far passare il bilanciere, poi distendi le braccia sopra la testa e riscendi controllando.', 'Inarcare la zona lombare per finire la spinta: tieni le costole basse e i glutei contratti in chiusura.'),
  ('endurance_cycling_recovery_spin', 'Pedalata di scarico (molto facile)', 'Pedalata leggerissima, su strada piana o sui rulli. Cadenza alta e agile con pochissima resistenza: l''andatura giusta è quella in cui parlare a frasi intere non costa niente. Si chiude con le gambe sciolte, non stanche.', 'Alzare la resistenza appena le gambe si sentono bene: così diventa un allenamento e non un recupero.'),
  ('gym_eccentric_tempo_rdl', 'Stacco rumeno a tempo eccentrico', 'In piedi col bilanciere davanti alle cosce, ginocchia appena morbide. Scendi lentamente mandando indietro il bacino e lasciando scorrere il bilanciere lungo le gambe finché senti tirare dietro le cosce, poi risali chiudendo le anche. La discesa è volutamente lenta.', 'Piegare le ginocchia per scendere più in basso: diventa uno stacco e i femorali smettono di allungarsi.'),
  ('empathy-b1-rowerg', 'Vogatore (remoergometro)', 'Seduto al vogatore, piedi legati e mani sulla maniglia. Ogni colpo parte dalla spinta delle gambe, poi apre il busto e infine tira le braccia al petto; il ritorno segue l''ordine inverso, più lento. Cerca un ritmo regolare e un respiro che resti sotto controllo.', 'Tirare con le braccia prima di aver spinto con le gambe: il colpo perde forza e la schiena si carica.'),
  ('empathy-b1-russiantwist', 'Russian twist (torsioni da seduto)', 'Seduto a terra con ginocchia piegate e busto inclinato indietro, piedi appoggiati o sollevati, mani unite o con una palla medica. Ruota il busto portando le mani da un lato all''altro senza far cadere il petto. Il movimento nasce dalla rotazione del tronco, non dalle braccia.', 'Muovere solo le braccia da un lato all''altro mentre il busto resta fermo: il tronco non ruota davvero.'),
  ('empathy-b1-sledpush', 'Sled push (spinta della slitta)', 'Impugna i montanti della slitta a braccia distese, busto inclinato avanti in linea con le gambe e sguardo poco davanti ai piedi. Spingi con passi corti e frequenti tenendo la slitta in movimento continuo: la spinta parte dalle gambe, le braccia tengono solo la linea.', 'Raddrizzare il busto quando ci si stanca: la slitta rallenta e la spinta passa tutta sulla schiena bassa.'),
  ('hyrox_sled_push', 'Sled push (spinta della slitta)', 'Impugna i montanti della slitta a braccia distese, busto inclinato avanti in linea con le gambe e sguardo poco davanti ai piedi. Spingi con passi corti e frequenti tenendo la slitta in movimento continuo: la spinta parte dalle gambe, le braccia tengono solo la linea.', 'Raddrizzare il busto quando ci si stanca: la slitta rallenta e la spinta passa tutta sulla schiena bassa.'),
  ('gym_cable_standing_row', 'Rematore ai cavi in piedi', 'In piedi davanti alla puleggia regolata all''altezza del petto, impugna la maniglia a braccia distese e arretra fino a mettere in tensione il cavo. Tira portando i gomiti indietro lungo i fianchi e avvicinando le scapole, poi lascia tornare avanti frenando il cavo. Busto fermo.', 'Accompagnare la trazione oscillando indietro col busto: il carico se lo prende la schiena bassa.'),
  ('crossfit_thruster', 'Thruster (squat e spinta sopra la testa)', 'Bilanciere o manubri in appoggio sulle spalle, gomiti alti, piedi a larghezza spalle. Scendi in squat fino in fondo e, appena risali, usa la spinta delle gambe per lanciare il carico sopra la testa fino a braccia distese. Il gesto è unico e continuo, senza pausa in mezzo.', 'Fermarsi in piedi prima di spingere: si perde la spinta delle gambe e le spalle devono alzare tutto da sole.'),
  ('empathy-b1-thruster', 'Thruster (squat e spinta sopra la testa)', 'Bilanciere o manubri in appoggio sulle spalle, gomiti alti, piedi a larghezza spalle. Scendi in squat fino in fondo e, appena risali, usa la spinta delle gambe per lanciare il carico sopra la testa fino a braccia distese. Il gesto è unico e continuo, senza pausa in mezzo.', 'Fermarsi in piedi prima di spingere: si perde la spinta delle gambe e le spalle devono alzare tutto da sole.'),
  ('empathy-b1x-tibialisraise', 'Tibialis raise (sollevamento delle punte)', 'Schiena appoggiata al muro con i piedi avanti di un passo, o all''apposita macchina. Tenendo i talloni a terra, solleva le punte dei piedi verso le tibie il più in alto possibile, poi riportale giù piano. Il bruciore arriva davanti alla tibia, non nel polpaccio.', 'Staccare i talloni da terra per alzare di più le punte: il lavoro si sposta e la tibia non viene caricata.'),
  ('gym_wall_sit_isometric', 'Wall sit (isometria alla parete)', 'Schiena appoggiata al muro, piedi avanti a larghezza anche; scivola giù finché ginocchia e anche formano un angolo retto e le cosce sono parallele a terra. Resta fermo col peso su tutto il piede. Cede per prima la coscia: quando brucia, il bacino tende a risalire.', 'Far risalire lentamente il bacino per alleggerire le cosce: l''angolo si apre e l''isometria non lavora più.'),
  ('empathy-b1-weightedpullup', 'Trazioni zavorrate', 'Appeso alla sbarra a presa prona poco più larga delle spalle, con la cintura da zavorra o un manubrio fra i piedi. Tira portando i gomiti in basso finché il mento supera la sbarra, poi scendi controllando fino a braccia distese senza far oscillare il carico.', 'Prendere lo slancio con le gambe per partire: il carico dondola e la trazione diventa uno strappo.'),
  ('endurance_z2_cycling', 'Fondo lento in bici (strada o rulli)', 'Pedalata continua a ritmo conversazionale, su strada o sui rulli. Andatura regolare, tenibile a lungo: respiro controllato e cadenza fluida, senza strappi. Quando le frasi si spezzano per respirare, il ritmo è già troppo alto.', 'Trasformare le salite in sforzi intensi: rallenta o alleggerisci il rapporto per restare nell''andatura.')
) as v(id, name_it, how_to_it, common_mistake_it)
where e.id = v.id;

-- CONTROLLO (atteso: 55 righe tradotte, 0 senza istruzioni fra quelle tradotte):
--   select count(*) filter (where name_it is not null) as tradotti,
--          count(*) filter (where name_it is not null and (how_to_it is null or common_mistake_it is null)) as incompleti
--   from public.exercise;
